-- =============================================================================
-- LANDING TABLE: L_AP_INV_APPLICATION_BC
-- =============================================================================
-- Source: FscmTopModelAM.FinExtractAM.ApBiccExtractAM.PaidDisbursementScheduleExtractPVO
-- Underlying table: AP_INVOICE_PAYMENTS_ALL
-- Bridge table linking invoices to disbursements (CHECK_ID <-> INVOICE_ID).
--
-- SETUP (three steps):
--   0. Extract CSV from the BICC ZIP (pkg_bicc_common.extract_and_stage_csv)
--   1. Create the external table (defines the CSV structure)
--   2. Create the landing table as a copy of the external table structure
--
-- IF BICC SCHEMA CHANGES:
--   DROP TABLE L_AP_INV_APPLICATION_BC;
--   DROP TABLE EXT_AP_INV_APPLICATION_BC;
--   Re-run Step 1 with updated column_list, then re-run Step 2.
-- =============================================================================


-- Step 0: Extract CSV from ZIP and upload to Object Storage
BEGIN
  pkg_bicc_common.extract_and_stage_csv(
      p_file_name    => 'file_fscmtopmodelam_finextractam_apbiccextractam_paiddisbursementscheduleextractpvo-batch_REPLACE_ME.zip',
      p_staging_name => 'staging/ap_inv_application_current.csv'
  );
END;
/


-- Step 1: Create external table (one-time, defines CSV structure)
-- 54 columns, alphabetical order per BICC convention.
BEGIN
  DBMS_CLOUD.CREATE_EXTERNAL_TABLE(
    table_name      => 'EXT_AP_INV_APPLICATION_BC',
    credential_name => '<OCI_CREDENTIAL_NAME>',
    file_uri_list   => 'https://objectstorage.us-ashburn-1.oraclecloud.com/n/<OCI_NAMESPACE>/b/<OCI_BUCKET_NAME>/o/staging/ap_inv_application_current.csv',
    format          => json_object(
                         'type' value 'csv',
                         'skipheaders' value '1'
                       ),
    column_list     => 'APINVOICEPAYMENTSALLACCOUNTINGDATE VARCHAR2(4000),APINVOICEPAYMENTSALLACCOUNTINGEVENTID VARCHAR2(4000),APINVOICEPAYMENTSALLACCTSPAYCODECOMBINATIONID VARCHAR2(4000),APINVOICEPAYMENTSALLAMOUNT VARCHAR2(4000),APINVOICEPAYMENTSALLAMOUNTINVCURR VARCHAR2(4000),APINVOICEPAYMENTSALLANNUALPERCENTAGERATE VARCHAR2(4000),APINVOICEPAYMENTSALLAPRASSIGNMENTID VARCHAR2(4000),APINVOICEPAYMENTSALLASSETCODECOMBINATIONID VARCHAR2(4000),APINVOICEPAYMENTSALLASSETSADDITIONFLAG VARCHAR2(4000),APINVOICEPAYMENTSALLBANKACCOUNTNUM VARCHAR2(4000),APINVOICEPAYMENTSALLBANKACCOUNTTYPE VARCHAR2(4000),APINVOICEPAYMENTSALLBANKNUM VARCHAR2(4000),APINVOICEPAYMENTSALLCHECKID VARCHAR2(4000),APINVOICEPAYMENTSALLCREATEDBY VARCHAR2(4000),APINVOICEPAYMENTSALLCREATIONDATE VARCHAR2(4000),APINVOICEPAYMENTSALLDAYSACCELERATED VARCHAR2(4000),APINVOICEPAYMENTSALLDISCOUNTLOST VARCHAR2(4000),APINVOICEPAYMENTSALLDISCOUNTLOSTINVCURR VARCHAR2(4000),APINVOICEPAYMENTSALLDISCOUNTTAKEN VARCHAR2(4000),APINVOICEPAYMENTSALLDISCOUNTTAKENINVCURR VARCHAR2(4000),APINVOICEPAYMENTSALLEXCHANGEDATE VARCHAR2(4000),APINVOICEPAYMENTSALLEXCHANGERATE VARCHAR2(4000),APINVOICEPAYMENTSALLEXCHANGERATETYPE VARCHAR2(4000),APINVOICEPAYMENTSALLEXTERNALBANKACCOUNTID VARCHAR2(4000),APINVOICEPAYMENTSALLGAINCODECOMBINATIONID VARCHAR2(4000),APINVOICEPAYMENTSALLIBANNUMBER VARCHAR2(4000),APINVOICEPAYMENTSALLINVORGID VARCHAR2(4000),APINVOICEPAYMENTSALLINVOICEBASEAMOUNT VARCHAR2(4000),APINVOICEPAYMENTSALLINVOICECURRENCYCODE VARCHAR2(4000),APINVOICEPAYMENTSALLINVOICEID VARCHAR2(4000),APINVOICEPAYMENTSALLINVOICEPAYMENTID VARCHAR2(4000),APINVOICEPAYMENTSALLINVOICEPAYMENTTYPE VARCHAR2(4000),APINVOICEPAYMENTSALLINVOICINGPARTYID VARCHAR2(4000),APINVOICEPAYMENTSALLINVOICINGPARTYSITEID VARCHAR2(4000),APINVOICEPAYMENTSALLINVOICINGVENDORSITEID VARCHAR2(4000),APINVOICEPAYMENTSALLLASTUPDATEDATE VARCHAR2(4000),APINVOICEPAYMENTSALLLASTUPDATELOGIN VARCHAR2(4000),APINVOICEPAYMENTSALLLASTUPDATEDBY VARCHAR2(4000),APINVOICEPAYMENTSALLLOSSCODECOMBINATIONID VARCHAR2(4000),APINVOICEPAYMENTSALLOBJECTVERSIONNUMBER VARCHAR2(4000),APINVOICEPAYMENTSALLORGID VARCHAR2(4000),APINVOICEPAYMENTSALLPAYMENTBASEAMOUNT VARCHAR2(4000),APINVOICEPAYMENTSALLPAYMENTCURRENCYCODE VARCHAR2(4000),APINVOICEPAYMENTSALLPAYMENTNUM VARCHAR2(4000),APINVOICEPAYMENTSALLPERIODNAME VARCHAR2(4000),APINVOICEPAYMENTSALLPOSTEDFLAG VARCHAR2(4000),APINVOICEPAYMENTSALLREMITTOADDRESSID VARCHAR2(4000),APINVOICEPAYMENTSALLREMITTOADDRESSNAME VARCHAR2(4000),APINVOICEPAYMENTSALLREMITTOSUPPLIERID VARCHAR2(4000),APINVOICEPAYMENTSALLREMITTOSUPPLIERNAME VARCHAR2(4000),APINVOICEPAYMENTSALLREVERSALFLAG VARCHAR2(4000),APINVOICEPAYMENTSALLREVERSALINVPMTID VARCHAR2(4000),APINVOICEPAYMENTSALLSETOFBOOKSID VARCHAR2(4000),APINVOICEPAYMENTSALLXCURRRATE VARCHAR2(4000)'
  );
END;
/

-- Step 2: Create landing table from the external table structure
CREATE TABLE L_AP_INV_APPLICATION_BC AS SELECT * FROM EXT_AP_INV_APPLICATION_BC WHERE 1=0;
