-- =============================================================================
-- PO LINES  Final Table
-- PK: ID (identity), UK: POLINEID, FK: POHEADERID -> PO_HDR_BC
-- Note: This table uses a surrogate identity PK + unique key on POLINEID,
--       rather than the standard BICC pattern. No JOB_ID / _RAW columns.
-- =============================================================================
CREATE TABLE PO_LINES_BC (
    ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    LOAD_TS         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    POHEADERID      NUMBER(18,0),
    POLINEID        NUMBER(18,0),
    LINENUM         NUMBER(10,0),
    CREATEDBY       VARCHAR2(255),
    CREATIONDATE    TIMESTAMP(6),
    FUNDSSTATUS     VARCHAR2(30),
    ITEMDESCRIPTION VARCHAR2(4000),
    LASTUPDATEDBY   VARCHAR2(255),
    LINESTATUS      VARCHAR2(30),
    LISTPRICE       NUMBER(18,5),
    MATCHINGBASIS   VARCHAR2(30),
    PURCHASEBASIS   VARCHAR2(30),
    SHIPPINGUOMCODE VARCHAR2(30),
    UNITPRICE       NUMBER(18,5),
    UOMCODE         VARCHAR2(30),
    CONSTRAINT FBX_PO_LINES_PK  PRIMARY KEY (ID),
    CONSTRAINT FBX_PO_LINES_UK1 UNIQUE (POLINEID)
);

CREATE INDEX FBX_PO_LINES_N1 ON PO_LINES_BC (POHEADERID, LINENUM);
CREATE INDEX FBX_PO_LINES_N2 ON PO_LINES_BC (POHEADERID);
