
  CREATE TABLE "S_SUPPLIER_HDR_BC" 
   (	"JOB_ID" NUMBER NOT NULL ENABLE, 
	"VENDORID" NUMBER(18,0), 
	"PARTYID" NUMBER(18,0), 
	"SEGMENT1" VARCHAR2(30), 
	"ALTERNATENAMEPARTYNAME" VARCHAR2(360), 
	"ALTERNATENAMEPARTYNAMEID" NUMBER(18,0), 
	"ALIASPARTYNAME" VARCHAR2(360), 
	"ALIASPARTYNAMEID" NUMBER(18,0), 
	"BUSINESSRELATIONSHIP" VARCHAR2(50), 
	"BCNOTAPPLICABLEFLAG" VARCHAR2(1), 
	"FEDERALREPORTABLEFLAG" VARCHAR2(1), 
	"INCOMETAXID" VARCHAR2(30), 
	"INCOMETAXIDFLAG" VARCHAR2(1), 
	"ORGANIZATIONTYPELOOKUPCODE" VARCHAR2(30), 
	"TYPE1099" VARCHAR2(30), 
	"VENDORTYPELOOKUPCODE" VARCHAR2(30), 
	"CREATEDBY" VARCHAR2(64), 
	"CREATIONDATE_RAW" VARCHAR2(50), 
	"CREATIONDATE_TS" TIMESTAMP (6), 
	"CREATIONSOURCE" VARCHAR2(30), 
	"LASTUPDATEDBY" VARCHAR2(64), 
	"LASTUPDATEDATE_RAW" VARCHAR2(50), 
	"LASTUPDATEDATE_TS" TIMESTAMP (6), 
	"LASTUPDATELOGIN" VARCHAR2(64), 
	"OBJECTVERSIONNUMBER" NUMBER(10,0), 
	"LAST_EXTRACT_RUN_ID" VARCHAR2(64), 
	"LAST_EXTRACT_RUN_TS" TIMESTAMP (6)
   ) ;

  CREATE INDEX "S_SUPPLIER_HDR_BC_I1" ON "S_SUPPLIER_HDR_BC" ("JOB_ID") 
  ;

  CREATE INDEX "S_SUPPLIER_HDR_BC_I2" ON "S_SUPPLIER_HDR_BC" ("JOB_ID", "VENDORID") 
  ;