
  CREATE TABLE "SUPPLIER_HDR_BC" 
   (	"VENDORID" NUMBER(18,0) NOT NULL ENABLE, 
	"PARTYID" NUMBER(18,0), 
	"SEGMENT1" VARCHAR2(30), 
	"ALTERNATENAMEPARTYNAME" VARCHAR2(360), 
	"ALTERNATENAMEPARTYNAMEID" NUMBER(18,0), 
	"ALIASPARTYNAME" VARCHAR2(360), 
	"ALIASPARTYNAMEID" NUMBER(18,0), 
	"BUSINESSRELATIONSHIP" VARCHAR2(50), 
	"BCNOTAPPLICABLEFLAG" VARCHAR2(1), 
	"FEDERALREPORTABLEFLAG" VARCHAR2(1), 
	"INCOMETAXID" VARCHAR2(30), 
	"INCOMETAXIDFLAG" VARCHAR2(1), 
	"ORGANIZATIONTYPELOOKUPCODE" VARCHAR2(30), 
	"TYPE1099" VARCHAR2(30), 
	"VENDORTYPELOOKUPCODE" VARCHAR2(30), 
	"CREATEDBY" VARCHAR2(64), 
	"CREATIONDATE" TIMESTAMP (6), 
	"CREATIONSOURCE" VARCHAR2(30), 
	"LASTUPDATEDBY" VARCHAR2(64), 
	"LASTUPDATEDATE" TIMESTAMP (6), 
	"LASTUPDATELOGIN" VARCHAR2(64), 
	"OBJECTVERSIONNUMBER" NUMBER(10,0), 
	"LAST_EXTRACT_RUN_ID" VARCHAR2(64), 
	"LAST_EXTRACT_RUN_TS" TIMESTAMP (6), 
	 CONSTRAINT "FBX_FUSION_SUPPLIER_HDR_PK" PRIMARY KEY ("VENDORID")
  USING INDEX  ENABLE
   ) ;

  CREATE INDEX "FBX_FUSION_SUPPLIER_HDR_I1" ON "SUPPLIER_HDR_BC" ("SEGMENT1") 
  ;

  CREATE INDEX "FBX_FUSION_SUPPLIER_HDR_I2" ON "SUPPLIER_HDR_BC" ("PARTYID") 
  ;