
  CREATE TABLE "HCM_ASSIGNMENT_BC"
   (	"ASSIGNMENT_ID" NUMBER,
	"PERSON_ID" NUMBER,
	"POSITION_ID" NUMBER,
	"ASSIGNMENT_NAME" VARCHAR2(400),
	"ASSIGNMENT_NUMBER" VARCHAR2(30),
	"ASSIGNMENT_STATUS_TYPE" VARCHAR2(30),
	"ASSIGNMENT_TYPE" VARCHAR2(10),
	"SYSTEM_PERSON_TYPE" VARCHAR2(30),
	"NORMAL_HOURS" NUMBER(10,2),
	"PRIMARY_ASSIGNMENT_FLAG" VARCHAR2(1),
	"PRIMARY_FLAG" VARCHAR2(1),
	"MANAGER_FLAG" VARCHAR2(1),
	"BUSINESS_UNIT_ID" NUMBER,
	"ORGANIZATION_ID" NUMBER,
	"LOCATION_ID" NUMBER,
	"HOURLY_SALARIED_CODE" VARCHAR2(10),
	"EMPLOYEE_CATEGORY" VARCHAR2(30),
	"EFFECTIVE_START_TS" TIMESTAMP (6),
	"EFFECTIVE_END_TS" TIMESTAMP (6),
	"LAST_EXTRACT_RUN_ID" VARCHAR2(64),
	"LAST_EXTRACT_RUN_TS" TIMESTAMP (6),
	 PRIMARY KEY ("ASSIGNMENT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE INDEX "FBX_HCM_ASSIGNMENT_N1" ON "HCM_ASSIGNMENT_BC" ("PERSON_ID")
  ;

  CREATE INDEX "FBX_HCM_ASSIGNMENT_N2" ON "HCM_ASSIGNMENT_BC" ("POSITION_ID")
  ;

  CREATE INDEX "FBX_HCM_ASSIGNMENT_N3" ON "HCM_ASSIGNMENT_BC" ("ASSIGNMENT_NUMBER")
  ;
