
  CREATE TABLE "HCM_POSITION_BC"
   (	"POSITION_ID" NUMBER,
	"POSITION_CODE" VARCHAR2(30),
	"POSITION_NAME" VARCHAR2(400),
	"ACTIVE_STATUS" VARCHAR2(10),
	"POSITION_TYPE" VARCHAR2(30),
	"FTE" NUMBER(10,6),
	"FULL_PART_TIME" VARCHAR2(30),
	"STANDARD_WORKING_HOURS" NUMBER(10,2),
	"ORGANIZATION_ID" NUMBER,
	"LOCATION_ID" NUMBER,
	"POSITION_JOB_ID" NUMBER,
	"BUSINESS_UNIT_ID" NUMBER,
	"MAX_PERSONS" NUMBER,
	"BUDGETED_FLAG" VARCHAR2(1),
	"HIRING_STATUS" VARCHAR2(30),
	"ASSIGNMENT_CATEGORY" VARCHAR2(30),
	"PARENT_POSITION_CODE" VARCHAR2(30),
	"PARENT_POSITION_NAME" VARCHAR2(400),
	"PARENT_ORG_NAME" VARCHAR2(400),
	"EFFECTIVE_START_TS" TIMESTAMP (6),
	"EFFECTIVE_END_TS" TIMESTAMP (6),
	"LAST_EXTRACT_RUN_ID" VARCHAR2(64),
	"LAST_EXTRACT_RUN_TS" TIMESTAMP (6),
	 PRIMARY KEY ("POSITION_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE INDEX "FBX_HCM_POSITION_N1" ON "HCM_POSITION_BC" ("POSITION_CODE")
  ;

  CREATE INDEX "FBX_HCM_POSITION_N2" ON "HCM_POSITION_BC" ("ORGANIZATION_ID")
  ;
