-- =============================================================================
-- LANDING TABLE: L_HCM_POSITION_BC
-- =============================================================================
-- COPY_DATA loads the raw CSV into this table.
-- The load procedure then cherry-picks columns into stg_fbx_hcm_position.
--
-- SETUP (two steps):
--   1. Create the external table (defines the CSV structure)
--   2. Create the landing table as a copy of the external table structure
--
-- IF BICC SCHEMA CHANGES:
--   DROP TABLE L_HCM_POSITION_BC;
--   DROP TABLE EXT_HCM_POSITION_BC;
--   Re-run Step 1 with updated column_list, then re-run Step 2.
-- =============================================================================


-- Step 1: Create external table (one-time, defines CSV structure)
-- Column order must match the BICC PositionPVOViewAll CSV header exactly.
BEGIN
  DBMS_CLOUD.CREATE_EXTERNAL_TABLE(
    table_name      => 'EXT_HCM_POSITION_BC',
    credential_name => '<OCI_CREDENTIAL_NAME>',
    file_uri_list   => 'https://objectstorage.us-ashburn-1.oraclecloud.com/n/<OCI_NAMESPACE>/b/<OCI_BUCKET_NAME>/o/hcm_position_unzipped.csv',
    format          => json_object(
                         'type' value 'csv',
                         'skipheaders' value '1'
                       ),
    column_list     => 'ACTIONOCCURRENCESPEOLASTUPDATEDATE VARCHAR2(4000),ACTIONREASONSPEOLASTUPDATEDATE VARCHAR2(4000),ACTIONREASONSTRANSLATIONPEOACTIONREASON VARCHAR2(4000),ACTIONREASONSTRANSLATIONPEOLASTUPDATEDATE VARCHAR2(4000),DELEGATEPOSITIONORGUNITPEOEFFECTIVESTARTDATE VARCHAR2(4000),DELEGATEPOSITIONORGUNITPEOLASTUPDATEDATE VARCHAR2(4000),DELEGATEPOSITIONORGUNITTLPEOEFFECTIVESTARTDATE VARCHAR2(4000),DELEGATEPOSITIONORGUNITTLPEOLASTUPDATEDATE VARCHAR2(4000),DELEGATEPOSITIONORGUNITTLPEONAME VARCHAR2(4000),DELEGATEPOSITIONPEOEFFECTIVESTARTDATE VARCHAR2(4000),DELEGATEPOSITIONPEOLASTUPDATEDATE VARCHAR2(4000),DELEGATEPOSITIONPEOPOSITIONCODE VARCHAR2(4000),DELEGATEPOSITIONTRANSLATIONPEOEFFECTIVESTARTDATE VARCHAR2(4000),DELEGATEPOSITIONTRANSLATIONPEOLASTUPDATEDATE VARCHAR2(4000),DELEGATEPOSITIONTRANSLATIONPEONAME VARCHAR2(4000),EFFECTIVEENDDATE VARCHAR2(4000),EFFECTIVESTARTDATE VARCHAR2(4000),JOBEVALUATIONPEOACCOUNTABILITY VARCHAR2(4000),JOBEVALUATIONPEOCREATEDBY VARCHAR2(4000),JOBEVALUATIONPEOCREATIONDATE VARCHAR2(4000),JOBEVALUATIONPEODATEEVALUATED VARCHAR2(4000),JOBEVALUATIONPEOEVALUATIONSYSTEM VARCHAR2(4000),JOBEVALUATIONPEOJOBEVALUATIONID VARCHAR2(4000),JOBEVALUATIONPEOKNOWHOW VARCHAR2(4000),JOBEVALUATIONPEOLASTUPDATEDATE VARCHAR2(4000),JOBEVALUATIONPEOLASTUPDATEDBY VARCHAR2(4000),JOBEVALUATIONPEOMEASUREDIN VARCHAR2(4000),JOBEVALUATIONPEOOVERALLSCORE VARCHAR2(4000),JOBEVALUATIONPEOPROBLEMSOLVING VARCHAR2(4000),PARENTPOSITIONORGUNITPEOEFFECTIVESTARTDATE VARCHAR2(4000),PARENTPOSITIONORGUNITPEOLASTUPDATEDATE VARCHAR2(4000),PARENTPOSITIONORGUNITTLPEOEFFECTIVESTARTDATE VARCHAR2(4000),PARENTPOSITIONORGUNITTLPEOLASTUPDATEDATE VARCHAR2(4000),PARENTPOSITIONORGUNITTLPEONAME VARCHAR2(4000),PARENTPOSITIONPEOEFFECTIVESTARTDATE VARCHAR2(4000),PARENTPOSITIONPEOLASTUPDATEDATE VARCHAR2(4000),PARENTPOSITIONPEOPOSITIONCODE VARCHAR2(4000),PARENTPOSITIONPEOPOSITIONID VARCHAR2(4000),PARENTPOSITIONTRANSLATIONPEOEFFECTIVESTARTDATE VARCHAR2(4000),PARENTPOSITIONTRANSLATIONPEOLASTUPDATEDATE VARCHAR2(4000),PARENTPOSITIONTRANSLATIONPEONAME VARCHAR2(4000),POSITIONHIERARCHYPEOEFFECTIVESTARTDATE1 VARCHAR2(4000),POSITIONHIERARCHYPEOLASTUPDATEDATE VARCHAR2(4000),POSITIONID VARCHAR2(4000),POSITIONPEOACTIONOCCURRENCEID VARCHAR2(4000),POSITIONPEOACTIVESTATUS VARCHAR2(4000),POSITIONPEOASSIGNMENTCATEGORY VARCHAR2(4000),POSITIONPEOATTRIBUTECATEGORY VARCHAR2(4000),POSITIONPEOBARGAININGUNITCD VARCHAR2(4000),POSITIONPEOBUDGETAMOUNT VARCHAR2(4000),POSITIONPEOBUDGETAMOUNTCURRENCY VARCHAR2(4000),POSITIONPEOBUDGETEDPOSITIONFLAG VARCHAR2(4000),POSITIONPEOBUSINESSGROUPID VARCHAR2(4000),POSITIONPEOBUSINESSUNITID VARCHAR2(4000),POSITIONPEOCREATEDBY VARCHAR2(4000),POSITIONPEOCREATIONDATE VARCHAR2(4000),POSITIONPEODELEGATEPOSITIONID VARCHAR2(4000),POSITIONPEOENTRYGRADEID VARCHAR2(4000),POSITIONPEOENTRYSTEPID VARCHAR2(4000),POSITIONPEOFREQUENCY VARCHAR2(4000),POSITIONPEOFTE VARCHAR2(4000),POSITIONPEOFULLPARTTIME VARCHAR2(4000),POSITIONPEOFUNDEDBYEXISTINGPOSITION VARCHAR2(4000),POSITIONPEOHIRINGSTATUS VARCHAR2(4000),POSITIONPEOJOBID VARCHAR2(4000),POSITIONPEOLASTUPDATEDATE VARCHAR2(4000),POSITIONPEOLASTUPDATELOGIN VARCHAR2(4000),POSITIONPEOLASTUPDATEDBY VARCHAR2(4000),POSITIONPEOLOCATIONID VARCHAR2(4000),POSITIONPEOMAXPERSONS VARCHAR2(4000),POSITIONPEOORGANIZATIONID VARCHAR2(4000),POSITIONPEOOVERLAPALLOWED VARCHAR2(4000),POSITIONPEOPERMANENTTEMPORARYFLAG VARCHAR2(4000),POSITIONPEOPOSITIONCODE VARCHAR2(4000),POSITIONPEOPOSITIONSYNCHRONIZATIONFLAG VARCHAR2(4000),POSITIONPEOPOSITIONTYPE VARCHAR2(4000),POSITIONPEOPROBATIONPERIOD VARCHAR2(4000),POSITIONPEOPROBATIONPERIODUNITCD VARCHAR2(4000),POSITIONPEOREQUISITIONTEMPLATEID VARCHAR2(4000),POSITIONPEOSEASONALENDDATE VARCHAR2(4000),POSITIONPEOSEASONALFLAG VARCHAR2(4000),POSITIONPEOSEASONALSTARTDATE VARCHAR2(4000),POSITIONPEOSECURITYCLEARANCE VARCHAR2(4000),POSITIONPEOSTANDARDWORKINGFREQUENCY VARCHAR2(4000),POSITIONPEOSTANDARDWORKINGHOURS VARCHAR2(4000),POSITIONPEOSUPERVISORASSIGNMENTID VARCHAR2(4000),POSITIONPEOSUPERVISORID VARCHAR2(4000),POSITIONPEOTIMENORMALFINISH VARCHAR2(4000),POSITIONPEOTIMENORMALSTART VARCHAR2(4000),POSITIONPEOWORKINGHOURS VARCHAR2(4000),POSITIONTRANSLATIONPEOEFFECTIVESTARTDATE VARCHAR2(4000),POSITIONTRANSLATIONPEOLANGUAGE VARCHAR2(4000),POSITIONTRANSLATIONPEOLASTUPDATEDATE VARCHAR2(4000),POSITIONTRANSLATIONPEONAME VARCHAR2(4000),REQUISITIONBPEOLASTUPDATEDATE VARCHAR2(4000),REQUISITIONBPEOREQUISITIONNUMBER VARCHAR2(4000),REQUISITIONTRANSLATEPEOLASTUPDATEDATE VARCHAR2(4000),REQUISITIONTRANSLATEPEOTITLE VARCHAR2(4000)'
  );
END;
/

-- Step 2: Create landing table from the external table structure
CREATE TABLE L_HCM_POSITION_BC AS SELECT * FROM EXT_HCM_POSITION_BC WHERE 1=0;
