-- =============================================================================
-- LANDING TABLE: L_HCM_ASSIGNMENT_BC
-- =============================================================================
-- COPY_DATA loads the raw CSV into this table.
-- The load procedure then cherry-picks columns into stg_fbx_hcm_assignment.
--
-- SETUP (two steps):
--   1. Create the external table (defines the CSV structure)
--   2. Create the landing table as a copy of the external table structure
--
-- IF BICC SCHEMA CHANGES:
--   DROP TABLE L_HCM_ASSIGNMENT_BC;
--   DROP TABLE EXT_HCM_ASSIGNMENT_BC;
--   Re-run Step 1 with updated column_list, then re-run Step 2.
-- =============================================================================


-- Step 1: Create external table (one-time, defines CSV structure)
-- Column order must match the BICC AssignmentPVO CSV header exactly.
-- The 36 field names below come from profiling the BICC extract.
-- ASSIGNMENTID is the top-level record identifier (first column).
BEGIN
  DBMS_CLOUD.CREATE_EXTERNAL_TABLE(
    table_name      => 'EXT_HCM_ASSIGNMENT_BC',
    credential_name => '<OCI_CREDENTIAL_NAME>',
    file_uri_list   => 'https://objectstorage.us-ashburn-1.oraclecloud.com/n/<OCI_NAMESPACE>/b/<OCI_BUCKET_NAME>/o/hcm_assignment_unzipped.csv',
    format          => json_object(
                         'type' value 'csv',
                         'skipheaders' value '1'
                       ),
    column_list     => 'ASSIGNMENTID VARCHAR2(4000),ASSIGNMENTPEOAPPLICANTRANK VARCHAR2(4000),ASSIGNMENTPEOASSIGNMENTNAME VARCHAR2(4000),ASSIGNMENTPEOASSIGNMENTNUMBER VARCHAR2(4000),ASSIGNMENTPEOASSIGNMENTSEQUENCE VARCHAR2(4000),ASSIGNMENTPEOASSIGNMENTSTATUSTYPE VARCHAR2(4000),ASSIGNMENTPEOASSIGNMENTTYPE VARCHAR2(4000),ASSIGNMENTPEOBARGAININGUNITCODE VARCHAR2(4000),ASSIGNMENTPEOBUSINESSUNITID VARCHAR2(4000),ASSIGNMENTPEOCREATEDBY VARCHAR2(4000),ASSIGNMENTPEOEMPLOYEECATEGORY VARCHAR2(4000),ASSIGNMENTPEOESTABLISHMENTID VARCHAR2(4000),ASSIGNMENTPEOFREQUENCY VARCHAR2(4000),ASSIGNMENTPEOHOURLYSALARIEDCODE VARCHAR2(4000),ASSIGNMENTPEOLABOURUNIONMEMBERFLAG VARCHAR2(4000),ASSIGNMENTPEOLASTUPDATEDATE VARCHAR2(4000),ASSIGNMENTPEOLOCATIONID VARCHAR2(4000),ASSIGNMENTPEOMANAGERFLAG VARCHAR2(4000),ASSIGNMENTPEONORMALHOURS VARCHAR2(4000),ASSIGNMENTPEONOTICEPERIOD VARCHAR2(4000),ASSIGNMENTPEOORGANIZATIONID VARCHAR2(4000),ASSIGNMENTPEOPERSONID VARCHAR2(4000),ASSIGNMENTPEOPOSITIONID VARCHAR2(4000),ASSIGNMENTPEOPRIMARYASSIGNMENTFLAG VARCHAR2(4000),ASSIGNMENTPEOPRIMARYFLAG VARCHAR2(4000),ASSIGNMENTPEOPROBATIONPERIOD VARCHAR2(4000),ASSIGNMENTPEOPROJECTEDASSIGNMENTEND VARCHAR2(4000),ASSIGNMENTPEOPROJECTEDSTARTDATE VARCHAR2(4000),ASSIGNMENTPEOPROPOSEDWORKERTYPE VARCHAR2(4000),ASSIGNMENTPEOSYSTEMPERSONTYPE VARCHAR2(4000),ASSIGNMENTPEOTIMENORMALFINISH VARCHAR2(4000),ASSIGNMENTPEOTIMENORMALSTART VARCHAR2(4000),ASSIGNMENTPEOWORKATHOME VARCHAR2(4000),EFFECTIVEENDDATE VARCHAR2(4000),EFFECTIVELATESTCHANGE VARCHAR2(4000),EFFECTIVESEQUENCE VARCHAR2(4000),EFFECTIVESTARTDATE VARCHAR2(4000)'
  );
END;
/

-- Step 2: Create landing table from the external table structure
CREATE TABLE L_HCM_ASSIGNMENT_BC AS SELECT * FROM EXT_HCM_ASSIGNMENT_BC WHERE 1=0;
