
  CREATE TABLE "S_HCM_POSITION_BC"
   (	"JOB_ID" NUMBER NOT NULL ENABLE,
	"POSITION_ID" NUMBER,
	"POSITION_CODE" VARCHAR2(30),
	"POSITION_NAME" VARCHAR2(400),
	"ACTIVE_STATUS" VARCHAR2(10),
	"POSITION_TYPE" VARCHAR2(30),
	"FTE" NUMBER(10,6),
	"FULL_PART_TIME" VARCHAR2(30),
	"STANDARD_WORKING_HOURS" NUMBER(10,2),
	"ORGANIZATION_ID" NUMBER,
	"LOCATION_ID" NUMBER,
	"POSITION_JOB_ID" NUMBER,
	"BUSINESS_UNIT_ID" NUMBER,
	"MAX_PERSONS" NUMBER,
	"BUDGETED_FLAG" VARCHAR2(1),
	"HIRING_STATUS" VARCHAR2(30),
	"ASSIGNMENT_CATEGORY" VARCHAR2(30),
	"PARENT_POSITION_CODE" VARCHAR2(30),
	"PARENT_POSITION_NAME" VARCHAR2(400),
	"PARENT_ORG_NAME" VARCHAR2(400),
	"EFFECTIVE_START_RAW" VARCHAR2(50),
	"EFFECTIVE_START_TS" TIMESTAMP (6),
	"EFFECTIVE_END_RAW" VARCHAR2(50),
	"EFFECTIVE_END_TS" TIMESTAMP (6),
	"LAST_EXTRACT_RUN_ID" VARCHAR2(64),
	"LAST_EXTRACT_RUN_TS" TIMESTAMP (6)
   ) ;

  CREATE INDEX "S_HCM_POSITION_BC_N1" ON "S_HCM_POSITION_BC" ("JOB_ID", "POSITION_ID")
  ;

  CREATE INDEX "S_HCM_POSITION_BC_N2" ON "S_HCM_POSITION_BC" ("JOB_ID", "POSITION_CODE")
  ;
