
  CREATE TABLE "S_HCM_ASSIGNMENT_BC"
   (	"JOB_ID" NUMBER NOT NULL ENABLE,
	"ASSIGNMENT_ID" NUMBER,
	"PERSON_ID" NUMBER,
	"POSITION_ID" NUMBER,
	"ASSIGNMENT_NAME" VARCHAR2(400),
	"ASSIGNMENT_NUMBER" VARCHAR2(30),
	"ASSIGNMENT_STATUS_TYPE" VARCHAR2(30),
	"ASSIGNMENT_TYPE" VARCHAR2(10),
	"SYSTEM_PERSON_TYPE" VARCHAR2(30),
	"NORMAL_HOURS" NUMBER(10,2),
	"PRIMARY_ASSIGNMENT_FLAG" VARCHAR2(1),
	"PRIMARY_FLAG" VARCHAR2(1),
	"MANAGER_FLAG" VARCHAR2(1),
	"BUSINESS_UNIT_ID" NUMBER,
	"ORGANIZATION_ID" NUMBER,
	"LOCATION_ID" NUMBER,
	"HOURLY_SALARIED_CODE" VARCHAR2(10),
	"EMPLOYEE_CATEGORY" VARCHAR2(30),
	"EFFECTIVE_START_RAW" VARCHAR2(50),
	"EFFECTIVE_START_TS" TIMESTAMP (6),
	"EFFECTIVE_END_RAW" VARCHAR2(50),
	"EFFECTIVE_END_TS" TIMESTAMP (6),
	"EFFECTIVE_SEQUENCE" NUMBER,
	"EFFECTIVE_LATEST_CHANGE" VARCHAR2(1),
	"LAST_EXTRACT_RUN_ID" VARCHAR2(64),
	"LAST_EXTRACT_RUN_TS" TIMESTAMP (6)
   ) ;

  CREATE INDEX "S_HCM_ASSIGNMENT_BC_N1" ON "S_HCM_ASSIGNMENT_BC" ("JOB_ID", "ASSIGNMENT_ID")
  ;

  CREATE INDEX "S_HCM_ASSIGNMENT_BC_N2" ON "S_HCM_ASSIGNMENT_BC" ("JOB_ID", "PERSON_ID")
  ;

  CREATE INDEX "S_HCM_ASSIGNMENT_BC_N3" ON "S_HCM_ASSIGNMENT_BC" ("JOB_ID", "POSITION_ID")
  ;
