
  CREATE TABLE "S_HCM_EMPLOYEE_BC" 
   (	"JOB_ID" NUMBER NOT NULL ENABLE, 
	"PERSON_ID" NUMBER, 
	"PERSON_NUMBER" VARCHAR2(30), 
	"DISPLAY_NAME" VARCHAR2(200), 
	"FIRST_NAME" VARCHAR2(100), 
	"LAST_NAME" VARCHAR2(100), 
	"KNOWN_AS" VARCHAR2(100), 
	"LEGISLATION_CODE" VARCHAR2(10), 
	"USER_NAME" VARCHAR2(200), 
	"USER_SUSPENDED_FLAG" VARCHAR2(1), 
	"WORK_EMAIL" VARCHAR2(200), 
	"PERSON_TYPE" VARCHAR2(30), 
	"HIRE_DATE_RAW" VARCHAR2(50), 
	"HIRE_DATE_TS" TIMESTAMP (6), 
	"TERMINATION_DATE_RAW" VARCHAR2(50), 
	"TERMINATION_DATE_TS" TIMESTAMP (6), 
	"ASSIGNMENT_ID" NUMBER, 
	"ASSIGNMENT_NUMBER" VARCHAR2(30), 
	"ASSIGNMENT_NAME" VARCHAR2(400), 
	"ASSIGNMENT_STATUS_TYPE" VARCHAR2(30), 
	"ASSIGNMENT_TYPE" VARCHAR2(10), 
	"EMPLOYMENT_CATEGORY" VARCHAR2(30), 
	"FULL_PART_TIME" VARCHAR2(30), 
	"HOURLY_SALARIED_CODE" VARCHAR2(10), 
	"NORMAL_HOURS" NUMBER(10,2), 
	"ASG_EFFECTIVE_START_RAW" VARCHAR2(50), 
	"ASG_EFFECTIVE_START_TS" TIMESTAMP (6), 
	"ASG_EFFECTIVE_END_RAW" VARCHAR2(50), 
	"ASG_EFFECTIVE_END_TS" TIMESTAMP (6), 
	"EFFECTIVE_LATEST_CHANGE_FLAG" VARCHAR2(1), 
	"PRIMARY_ASSIGNMENT_FLAG" VARCHAR2(1), 
	"PRIMARY_WORK_REL_FLAG" VARCHAR2(1), 
	"POSITION_CODE" VARCHAR2(30), 
	"POSITION_NAME" VARCHAR2(400), 
	"ORG_ID" NUMBER, 
	"ORG_NAME" VARCHAR2(400), 
	"LOCATION_NAME" VARCHAR2(400), 
	"ADDR_CITY" VARCHAR2(240), 
	"ADDR_STATE" VARCHAR2(60), 
	"ADDR_POSTAL_CODE" VARCHAR2(30), 
	"ADDR_COUNTRY" VARCHAR2(10), 
	"MANAGER_PERSON_ID" NUMBER, 
	"MANAGER_DISPLAY_NAME" VARCHAR2(200), 
	"MANAGER_EMAIL" VARCHAR2(200), 
	"MANAGER_USER_NAME" VARCHAR2(200), 
	"MANAGER_TYPE" VARCHAR2(30), 
	"LAST_EXTRACT_RUN_ID" VARCHAR2(64), 
	"LAST_EXTRACT_RUN_TS" TIMESTAMP (6)
   ) ;

  CREATE INDEX "S_HCM_EMPLOYEE_BC_N1" ON "S_HCM_EMPLOYEE_BC" ("JOB_ID", "PERSON_ID") 
  ;

  CREATE INDEX "S_HCM_EMPLOYEE_BC_N2" ON "S_HCM_EMPLOYEE_BC" ("JOB_ID", "PERSON_NUMBER") 
  ;

  CREATE INDEX "S_HCM_EMPLOYEE_BC_N3" ON "S_HCM_EMPLOYEE_BC" ("JOB_ID", "WORK_EMAIL") 
  ;