
  CREATE TABLE "BICC_FILES" 
   (	"FILE_NAME" VARCHAR2(500), 
	"FILE_SIZE" NUMBER, 
	"FILE_SIZE_KB" NUMBER, 
	"LAST_MODIFIED" TIMESTAMP (6), 
	"MODULE_CODE" VARCHAR2(100), 
	"OBJECT_CODE" VARCHAR2(100), 
	"LOAD_TYPE" VARCHAR2(200), 
	"LOADER_AVAILABLE" VARCHAR2(1), 
	"REFRESHED_TS" TIMESTAMP (6) DEFAULT systimestamp, 
	"FILE_TIMESTAMP" TIMESTAMP (9), 
	 PRIMARY KEY ("FILE_NAME")
  USING INDEX  ENABLE
   ) ;