-- =============================================================================
-- HCM_SALARY_R
-- APEX REST Data Source sync table — module static ID: rest_sync_salaries
-- Module code: HCM  |  Sync type: INCREMENTAL
-- APEX$ columns (APEX$RESOURCEKEY, APEX$SYNC_STEP_STATIC_ID,
--   APEX$ROW_SYNC_TIMESTAMP) are managed by APEX REST Data Sync
-- =============================================================================
CREATE TABLE HCM_SALARY_R (
    ASSIGNMENTID                  NUMBER,
    SALARYID                      NUMBER,
    SALARYBASISID                 NUMBER,
    SALARYFREQUENCYCODE           VARCHAR2(30),
    SALARYBASISTYPE               VARCHAR2(30),
    CURRENCYCODE                  VARCHAR2(30),
    DATEFROM                      DATE,
    DATETO                        DATE,
    SALARYAMOUNT                  NUMBER,
    ADJUSTMENTAMOUNT              NUMBER,
    ADJUSTMENTPERCENTAGE          NUMBER,
    ANNUALSALARY                  NUMBER,
    ANNUALFULLTIMESALARY          NUMBER,
    QUARTILE                      VARCHAR2(30),
    QUINTILE                      VARCHAR2(30),
    COMPARATIO                    NUMBER,
    RANGEPOSITION                 NUMBER,
    SALARYRANGEMINIMUM            NUMBER,
    SALARYRANGEMIDPOINT           NUMBER,
    SALARYRANGEMAXIMUM            NUMBER,
    SEARCHDATE                    VARCHAR2(32767),
    FREQUENCYNAME                 VARCHAR2(32767),
    ASSIGNMENTNUMBER              VARCHAR2(50),
    DISPLAYNAME                   VARCHAR2(80),
    ACTIONID                      NUMBER,
    ACTIONREASONID                NUMBER,
    ACTIONCODE                    VARCHAR2(30),
    ACTIONREASONCODE              VARCHAR2(30),
    ACTIONREASON                  VARCHAR2(80),
    ACTIONNAME                    VARCHAR2(80),
    CODE                          VARCHAR2(80),
    LEGALEMPLOYERNAME             VARCHAR2(255),
    GRADELADDERNAME               VARCHAR2(255),
    GRADENAME                     VARCHAR2(255),
    GRADESTEPNAME                 VARCHAR2(255),
    GEOGRAPHYNAME                 VARCHAR2(255),
    GEOGRAPHYTYPENAME             VARCHAR2(255),
    GRADEID                       NUMBER,
    LASTUPDATEDATE                TIMESTAMP(6) WITH TIME ZONE,
    LASTUPDATEDBY                 VARCHAR2(64),
    CREATEDBY                     VARCHAR2(64),
    CREATIONDATE                  TIMESTAMP(6) WITH TIME ZONE,
    FTEVALUE                      NUMBER,
    NEXTSALREVIEWDATE             DATE,
    ASSIGNMENTTYPE                VARCHAR2(30),
    SALARYBASISNAME               VARCHAR2(80),
    AMOUNTDECIMALPRECISION        NUMBER,
    SALARYAMOUNTSCALE             NUMBER,
    AMOUNTROUNDINGCODE            VARCHAR2(30),
    ANNUALROUNDINGCODE            VARCHAR2(30),
    RANGEROUNDINGCODE             VARCHAR2(30),
    WORKATHOME                    VARCHAR2(255),
    QUARTILEMEANING               VARCHAR2(255),
    QUINTILEMEANING               VARCHAR2(255),
    LEGISLATIVEDATAGROUPID        NUMBER,
    HASFUTURESALARY               VARCHAR2(255),
    MULTIPLECOMPONENTS            VARCHAR2(30),
    COMPONENTUSAGE                VARCHAR2(30),
    PENDINGTRANSACTIONEXISTS      VARCHAR2(255),
    RANGEERRORWARNING             VARCHAR2(30),
    PAYROLLFACTOR                 NUMBER,
    SALARYFACTOR                  NUMBER,
    PAYROLLFREQUENCYCODE          VARCHAR2(40),
    PERSONID                      NUMBER,
    BUSINESSTITLE                 VARCHAR2(80),
    PERSONNUMBER                  VARCHAR2(255),
    PERSONDISPLAYNAME             VARCHAR2(255),
    GRADECODE                     VARCHAR2(255),
    ACTIONOCCURRENCEID            NUMBER,
    SALARYTRANSACTIONSTATUS       VARCHAR2(20),
    ADJUSTEDANNUALFTSALARY        NUMBER,
    ADJUSTEDANNUALSALARY          NUMBER,
    ADJUSTEDFTEVALUE              NUMBER,
    SALARYRANGEDEFAULTVALUE       NUMBER,
    ADJUSTEDFTEUSAGE              VARCHAR2(30),
    CONSTRAINT REST_HCM_SALARY_PK PRIMARY KEY (APEX$RESOURCEKEY)
);
