-- =============================================================================
-- JOB_REQUISITIONS_R
-- APEX REST Data Source sync table — module static ID: rest_sync_job_requisitions
-- Module code: HCM  |  Sync type: INCREMENTAL
-- APEX$ columns (APEX$RESOURCEKEY, APEX$SYNC_STEP_STATIC_ID,
--   APEX$ROW_SYNC_TIMESTAMP) are managed by APEX REST Data Sync
-- =============================================================================
CREATE TABLE JOB_REQUISITIONS_R (
    REQUISITIONNUMBER                            VARCHAR2(240),
    REQUISITIONID                                NUMBER,
    TITLE                                        VARCHAR2(240),
    OTHERREQUISITIONTITLE                        VARCHAR2(240),
    RECRUITINGTYPE                               VARCHAR2(30),
    TEMPLATEID                                   NUMBER,
    PIPELINEREQUISITION                          VARCHAR2(1),
    PIPELINEREQUISITIONID                        NUMBER,
    STATEID                                      NUMBER,
    STATENAME                                    VARCHAR2(240),
    PHASEID                                      NUMBER,
    PHASENAME                                    VARCHAR2(240),
    POSITIONID                                   NUMBER,
    UNLIMITEDOPENINGS                            VARCHAR2(1),
    NUMBEROFOPENINGS                             NUMBER,
    HIREDCOUNT                                   NUMBER,
    APPLYWHENNOTPOSTED                           VARCHAR2(1),
    BUSINESSJUSTIFICATION                        VARCHAR2(30),
    DISPLAYINORGCHART                            VARCHAR2(1),
    HIRINGMANAGERID                              NUMBER,
    HIRINGMANAGERASSIGNMENTID                    NUMBER,
    RECRUITERID                                  NUMBER,
    RECRUITERASSIGNMENTID                        NUMBER,
    PROFILEID                                    NUMBER,
    ORGANIZATIONID                               NUMBER,
    JOBFAMILYID                                  NUMBER,
    JOBFUNCTION                                  VARCHAR2(30),
    BUSINESSUNITID                               NUMBER,
    DEPARTMENTID                                 NUMBER,
    PRIMARYWORKLOCATIONID                        NUMBER,
    PRIMARYLOCATIONID                            NUMBER,
    JOBID                                        NUMBER,
    GRADEID                                      NUMBER,
    LEGALEMPLOYERID                              NUMBER,
    BUDGETCURRENCY                               VARCHAR2(30),
    EMPLOYEEREFERRALBONUS                        NUMBER,
    SOURCINGBUDGET                               NUMBER,
    TRAVELBUDGET                                 NUMBER,
    RELOCATIONBUDGET                             NUMBER,
    COMPENSATIONCURRENCY                         VARCHAR2(30),
    MINIMUMSALARY                                NUMBER,
    MAXIMUMSALARY                                NUMBER,
    PAYFREQUENCY                                 VARCHAR2(30),
    WORKERTYPE                                   VARCHAR2(30),
    REGULARORTEMPORARY                           VARCHAR2(30),
    MANAGEMENTLEVEL                              VARCHAR2(30),
    FULLTIMEORPARTTIME                           VARCHAR2(30),
    JOBSHIFT                                     VARCHAR2(30),
    JOBTYPE                                      VARCHAR2(30),
    EDUCATIONLEVEL                               VARCHAR2(30),
    INTERNALCONTACTNAME                          VARCHAR2(240),
    INTERNALCONTACTEMAIL                         VARCHAR2(240),
    EXTERNALCONTACTNAME                          VARCHAR2(240),
    EXTERNALCONTACTEMAIL                         VARCHAR2(240),
    EMPLOYERINTERNALDESCRIPTIONID                NUMBER,
    EMPLOYEREXTERNALDESCRIPTIONID                NUMBER,
    RECRUITINGORGANIZATIONINTERNALDESCRIPTIONID  NUMBER,
    RECRUITINGORGANIZATIONEXTERNALDESCRIPTIONID  NUMBER,
    INTERNALPUBLISHEDJOBSTARTDATE                TIMESTAMP(6) WITH TIME ZONE,
    INTERNALPUBLISHEDJOBENDDATE                  TIMESTAMP(6) WITH TIME ZONE,
    INTERNALPUBLISHEDJOBSTATUS                   VARCHAR2(30),
    EXTERNALPUBLISHEDJOBSTARTDATE                TIMESTAMP(6) WITH TIME ZONE,
    EXTERNALPUBLISHEDJOBENDDATE                  TIMESTAMP(6) WITH TIME ZONE,
    EXTERNALPUBLISHEDJOBSTATUS                   VARCHAR2(30),
    EXTERNALAPPLICATIONFLOWID                    NUMBER,
    CANDIDATESELECTIONPROCESSID                  NUMBER,
    REQUISITIONLASTMODIFIEDDATE                  TIMESTAMP(6) WITH TIME ZONE,
    CREATEDBY                                    VARCHAR2(64),
    CREATIONDATE                                 TIMESTAMP(6) WITH TIME ZONE,
    LASTUPDATEDBY                                VARCHAR2(64),
    LASTUPDATEDATE                               TIMESTAMP(6) WITH TIME ZONE,
    AUTOMATICALLYOPENREQUISITIONFORSOURCING      VARCHAR2(30),
    DELAYBEFOREPOSTINGEXPIRES                    NUMBER,
    INTERNALRESPSTR                              VARCHAR2(255),
    EXTERNALRESPSTR                              VARCHAR2(255),
    INTERNALQUALSTR                              VARCHAR2(255),
    EXTERNALQUALSTR                              VARCHAR2(255),
    WORKPLACETYPECODE                            VARCHAR2(30),
    WORKENDDATE                                  TIMESTAMP(6) WITH TIME ZONE,
    WORKSTARTDATE                                TIMESTAMP(6) WITH TIME ZONE,
    SALARYPERIODCODE                             VARCHAR2(30),
    CONSTRAINT REST_JOB_REQUISITIONS_PK PRIMARY KEY (APEX$RESOURCEKEY)
);
