-- =============================================================================
-- SUPPLIERS_R
-- APEX REST Data Source sync table — module static ID: rest_sync_suppliers
-- Module code: PRC  |  Sync type: FULL_ONLY
-- APEX$ columns (APEX$RESOURCEKEY, APEX$SYNC_STEP_STATIC_ID,
--   APEX$ROW_SYNC_TIMESTAMP) are managed by APEX REST Data Sync
-- =============================================================================
CREATE TABLE SUPPLIERS_R (
    SUPPLIERID                               NUMBER,
    SUPPLIERPARTYID                          NUMBER,
    SUPPLIER                                 VARCHAR2(360),
    SUPPLIERNUMBER                           VARCHAR2(30),
    ALTERNATENAME                            VARCHAR2(360),
    TAXORGANIZATIONTYPECODE                  VARCHAR2(30),
    TAXORGANIZATIONTYPE                      VARCHAR2(80),
    SUPPLIERTYPECODE                         VARCHAR2(30),
    SUPPLIERTYPE                             VARCHAR2(80),
    INACTIVEDATE                             DATE,
    STATUS                                   VARCHAR2(255),
    BUSINESSRELATIONSHIPCODE                 VARCHAR2(30),
    BUSINESSRELATIONSHIP                     VARCHAR2(80),
    RELATIONSHIPDISPLAY                      VARCHAR2(255),
    REQUESTNUMBER                            NUMBER,
    PARENTSUPPLIERID                         NUMBER,
    PARENTSUPPLIER                           VARCHAR2(360),
    PARENTSUPPLIERNUMBER                     VARCHAR2(30),
    CREATIONDATE                             TIMESTAMP(6) WITH TIME ZONE,
    CREATEDBY                                VARCHAR2(64),
    LASTUPDATEDATE                           TIMESTAMP(6) WITH TIME ZONE,
    LASTUPDATEDBY                            VARCHAR2(64),
    CREATIONSOURCECODE                       VARCHAR2(25),
    CREATIONSOURCE                           VARCHAR2(80),
    DATAFOXSCORE                             NUMBER,
    DATAFOXSCORINGCRITERIA                   VARCHAR2(4000),
    ALIAS                                    VARCHAR2(360),
    DUNSNUMBER                               VARCHAR2(30),
    ONETIMESUPPLIERFLAG                      VARCHAR2(5),
    REGISTRYID                               VARCHAR2(30),
    CUSTOMERNUMBER                           VARCHAR2(25),
    STANDARDINDUSTRYCLASS                    VARCHAR2(25),
    INDUSTRYCATEGORY                         VARCHAR2(30),
    INDUSTRYSUBCATEGORY                      VARCHAR2(30),
    NATIONALINSURANCENUMBER                  VARCHAR2(32767),
    NATIONALINSURANCENUMBEREXISTSFLAG        VARCHAR2(5),
    CORPORATEWEBSITE                         VARCHAR2(150),
    YEARESTABLISHED                          NUMBER,
    MISSIONSTATEMENT                         VARCHAR2(2000),
    YEARINCORPORATED                         NUMBER,
    CHIEFEXECUTIVETITLE                      VARCHAR2(240),
    CHIEFEXECUTIVENAME                       VARCHAR2(240),
    PRINCIPALTITLE                           VARCHAR2(240),
    PRINCIPALNAME                            VARCHAR2(240),
    FISCALYEARENDMONTHCODE                   VARCHAR2(30),
    FISCALYEARENDMONTH                       VARCHAR2(80),
    CURRENTFISCALYEARPOTENTIALREVENUE        NUMBER,
    PREFERREDFUNCTIONALCURRENCYCODE          VARCHAR2(15),
    PREFERREDFUNCTIONALCURRENCY              VARCHAR2(80),
    TAXREGISTRATIONCOUNTRYCODE               VARCHAR2(2),
    TAXREGISTRATIONCOUNTRY                   VARCHAR2(80),
    TAXREGISTRATIONNUMBER                    VARCHAR2(50),
    TAXPAYERCOUNTRYCODE                      VARCHAR2(2),
    TAXPAYERCOUNTRY                          VARCHAR2(80),
    TAXPAYERID                               VARCHAR2(30),
    TAXPAYERIDEXISTSFLAG                     VARCHAR2(5),
    FEDERALREPORTABLEFLAG                    VARCHAR2(5),
    FEDERALINCOMETAXTYPECODE                 VARCHAR2(10),
    FEDERALINCOMETAXTYPE                     VARCHAR2(80),
    STATEREPORTABLEFLAG                      VARCHAR2(5),
    TAXREPORTINGNAME                         VARCHAR2(80),
    NAMECONTROL                              VARCHAR2(4),
    VERIFICATIONDATE                         DATE,
    USEWITHHOLDINGTAXFLAG                    VARCHAR2(5),
    WITHHOLDINGTAXGROUPID                    NUMBER,
    WITHHOLDINGTAXGROUP                      VARCHAR2(25),
    BUSINESSCLASSIFICATIONNOTAPPLICABLEFLAG  VARCHAR2(5),
    SPENDAUTHREVIEWSTATUS                    VARCHAR2(30),
    SPENDAUTHREVIEWSTATUSDISPLAY             VARCHAR2(80),
    DATAFOXID                                VARCHAR2(30),
    DATAFOXCOMPANYNAME                       VARCHAR2(360),
    DATAFOXLEGALNAME                         VARCHAR2(360),
    DATAFOXCOMPANYPRIMARYURL                 VARCHAR2(150),
    DATAFOXNAICSCODE                         VARCHAR2(25),
    DATAFOXCOUNTRY                           VARCHAR2(2),
    DATAFOXEIN                               VARCHAR2(30),
    DATAFOXLASTSYNCDATE                      TIMESTAMP(6) WITH TIME ZONE,
    OBNENABLEDFLAG                           VARCHAR2(5),
    ONOFACLISTFLAG                           VARCHAR2(5),
    OFACSOURCES                              VARCHAR2(4000),
    CONSTRAINT REST_SUPPLIERS_PK PRIMARY KEY (APEX$RESOURCEKEY)
);
