-- =============================================================================
-- LANDING TABLE: L_QSTNR_QUESTION_BC
-- =============================================================================
-- Source: HcmTopModelAnalyticsGlobalAM.QuestionnaireAM.ParticipantQuestionnaireQuestionPVO
-- COPY_DATA loads the raw CSV into this table.
-- The load procedure then cherry-picks columns into S_QSTNR_QUESTION_BC.
--
-- SETUP (three steps):
--   0. Extract CSV from the BICC ZIP (pkg_bicc_common.extract_and_stage_csv)
--   1. Create the external table (defines the CSV structure)
--   2. Create the landing table as a copy of the external table structure
--
-- IF BICC SCHEMA CHANGES:
--   DROP TABLE L_QSTNR_QUESTION_BC;
--   DROP TABLE EXT_QSTNR_QUESTION_BC;
--   Re-run Step 1 with updated column_list, then re-run Step 2.
-- =============================================================================


-- Step 0: Extract CSV from ZIP and upload to Object Storage
-- Replace the file name below with the actual BICC ZIP from your extract.
BEGIN
  pkg_bicc_common.extract_and_stage_csv(
      p_file_name    => 'file_hcmtopmodelanalyticsglobalam_questionnaream_participantquestionnairequestionpvo-batch_REPLACE_ME.zip',
      p_staging_name => 'staging/qstnr_question_current.csv'
  );
END;
/


-- Step 1: Create external table (one-time, defines CSV structure)
-- Column order matches the BICC CSV as-is (NOT alphabetical for PVO extracts).
BEGIN
  DBMS_CLOUD.CREATE_EXTERNAL_TABLE(
    table_name      => 'EXT_QSTNR_QUESTION_BC',
    credential_name => '<OCI_CREDENTIAL_NAME>',
    file_uri_list   => 'https://objectstorage.us-ashburn-1.oraclecloud.com/n/<OCI_NAMESPACE>/b/<OCI_BUCKET_NAME>/o/staging/qstnr_question_current.csv',
    format          => json_object(
                         'type' value 'csv',
                         'skipheaders' value '1'
                       ),
    column_list     => 'QUESTIONBPEOBUSINESSGROUPID VARCHAR2(4000),QUESTIONBPEOCLASSIFICATIONCODE VARCHAR2(4000),QUESTIONBPEOLASTUPDATEDATE VARCHAR2(4000),QUESTIONBPEOOWNER VARCHAR2(4000),QUESTIONBPEOPRIVACYFLAG VARCHAR2(4000),QUESTIONBPEOQSTNVERSIONNUM VARCHAR2(4000),QUESTIONBPEOQUESTIONCODE VARCHAR2(4000),QUESTIONBPEOQUESTIONID VARCHAR2(4000),QUESTIONBPEOQUESTIONTYPE VARCHAR2(4000),QUESTIONBPEOSTATUS VARCHAR2(4000),QUESTIONSECTIONTRANSLATIONPEOBUSINESSGROUPID VARCHAR2(4000),QUESTIONSECTIONTRANSLATIONPEOLANGUAGE VARCHAR2(4000),QUESTIONSECTIONTRANSLATIONPEONAME VARCHAR2(4000),QUESTIONSECTIONTRANSLATIONPEOQSTNRSECTIONID VARCHAR2(4000),QUESTIONTRANSLATIONPEOBUSINESSGROUPID VARCHAR2(4000),QUESTIONTRANSLATIONPEOLANGUAGE VARCHAR2(4000),QUESTIONTRANSLATIONPEOQSTNVERSIONNUM VARCHAR2(4000),QUESTIONTRANSLATIONPEOQUESTIONID VARCHAR2(4000),QUESTIONTRANSLATIONPEOQUESTIONTEXT VARCHAR2(4000),QUESTIONNAIREBPEOBUSINESSGROUPID VARCHAR2(4000),QUESTIONNAIREBPEOQSTNRVERSIONNUM VARCHAR2(4000),QUESTIONNAIREBPEOQUESTIONNAIRECODE VARCHAR2(4000),QUESTIONNAIREBPEOQUESTIONNAIREID VARCHAR2(4000),QUESTIONNAIREBPEOSTATUS VARCHAR2(4000),QUESTIONNAIREPARTICIPANTPEOBUSINESSGROUPID VARCHAR2(4000),QUESTIONNAIREPARTICIPANTPEOQSTNRPARTICIPANTID VARCHAR2(4000),QUESTIONNAIREPARTICIPANTPEOQUESTIONNAIREID VARCHAR2(4000),QUESTIONNAIREPARTICIPANTPEOSUBJECTID VARCHAR2(4000),QUESTIONNAIREQUESTIONPEOADHOCQSTN VARCHAR2(4000),QUESTIONNAIREQUESTIONPEOBUSINESSGROUPID VARCHAR2(4000),QUESTIONNAIREQUESTIONPEOLASTUPDATEDATE VARCHAR2(4000),QUESTIONNAIREQUESTIONPEOMANDATORY VARCHAR2(4000),QUESTIONNAIREQUESTIONPEOQSTNRQUESTIONID VARCHAR2(4000),QUESTIONNAIREQUESTIONPEOSEQNUM VARCHAR2(4000),QUESTIONNAIRESECTIONBPEOBUSINESSGROUPID VARCHAR2(4000),QUESTIONNAIRESECTIONBPEOLASTUPDATEDATE VARCHAR2(4000),QUESTIONNAIRESECTIONBPEOQSTNRSECTIONID VARCHAR2(4000),QUESTIONNAIRESECTIONBPEOQUESTIONORDER VARCHAR2(4000),QUESTIONNAIRESECTIONBPEOSECTIONSEQNUM VARCHAR2(4000),QUESTIONNAIRESECTIONTRANSLATIONPEOLASTUPDATEDATE VARCHAR2(4000),QUESTIONNAIRETLPEONAME VARCHAR2(4000),QUESTIONNAIRETRANSLATIONPEOCREATEDBY VARCHAR2(4000),QUESTIONNAIRETRANSLATIONPEOCREATIONDATE VARCHAR2(4000),QUESTIONNAIRETRANSLATIONPEOLASTUPDATEDATE VARCHAR2(4000),QUESTIONNAIRETRANSLATIONPEOLASTUPDATEDBY VARCHAR2(4000)'
  );
END;
/

-- Step 2: Create landing table from the external table structure
CREATE TABLE L_QSTNR_QUESTION_BC AS SELECT * FROM EXT_QSTNR_QUESTION_BC WHERE 1=0;
