-- NOTE: PK is QSTN_RESPONSE_ID (unique per individual question answer row).
-- If multi-select questions produce duplicate QSTN_RESPONSE_IDs with different
-- ANSWER_IDs, change PK to (QSTN_RESPONSE_ID, ANSWER_ID) and adjust the
-- MERGE in pkg_bicc_qstnr_response accordingly.

CREATE TABLE QSTNR_RESPONSE_BC
(
    QSTNR_RESPONSE_ID      NUMBER,
    QSTNR_PARTICIPANT_ID   NUMBER,
    RESPONSE_STATUS         VARCHAR2(10),
    ATTEMPT_NUM             NUMBER,
    SUBMITTED_DATE_TS       TIMESTAMP(6),
    QSTNR_QUESTION_ID      NUMBER,
    QSTN_RESPONSE_ID       NUMBER,
    ANSWER_CLOB             VARCHAR2(4000),
    ANSWER_ID               NUMBER,
    ANSWER_TYPE             VARCHAR2(30),
    SUBJECT_ID              NUMBER,
    LAST_UPDATE_DATE_TS     TIMESTAMP(6),
    LAST_EXTRACT_RUN_ID     VARCHAR2(64),
    LAST_EXTRACT_RUN_TS     TIMESTAMP(6),
    CONSTRAINT FBX_QSTNR_RESPONSE_PK PRIMARY KEY (QSTN_RESPONSE_ID)
);

CREATE INDEX FBX_QSTNR_RESPONSE_N1 ON QSTNR_RESPONSE_BC (QSTNR_PARTICIPANT_ID, QSTNR_QUESTION_ID);
CREATE INDEX FBX_QSTNR_RESPONSE_N2 ON QSTNR_RESPONSE_BC (SUBJECT_ID);
CREATE INDEX FBX_QSTNR_RESPONSE_N3 ON QSTNR_RESPONSE_BC (ANSWER_ID);
