CREATE TABLE QSTNR_QUESTION_BC
(
    QUESTIONNAIRE_ID              NUMBER,
    QUESTIONNAIRE_CODE            VARCHAR2(100),
    QSTNR_VERSION_NUM             NUMBER,
    QUESTIONNAIRE_STATUS          VARCHAR2(10),
    QUESTIONNAIRE_NAME            VARCHAR2(400),
    QUESTIONNAIRE_CREATED_BY      VARCHAR2(200),
    QUESTIONNAIRE_CREATION_DATE_TS  TIMESTAMP(6),
    QSTNR_SECTION_ID             NUMBER,
    SECTION_SEQ_NUM               NUMBER,
    SECTION_QUESTION_ORDER        VARCHAR2(10),
    SECTION_NAME                  VARCHAR2(400),
    QUESTION_ID                   NUMBER,
    QUESTION_CODE                 VARCHAR2(100),
    QUESTION_TYPE                 VARCHAR2(30),
    CLASSIFICATION_CODE           VARCHAR2(60),
    QSTN_VERSION_NUM              NUMBER,
    QUESTION_STATUS               VARCHAR2(10),
    QUESTION_TEXT                  VARCHAR2(4000),
    QSTNR_QUESTION_ID            NUMBER,
    QUESTION_SEQ_NUM              NUMBER,
    MANDATORY_FLAG                VARCHAR2(1),
    ADHOC_QUESTION_FLAG           VARCHAR2(1),
    QSTNR_PARTICIPANT_ID         NUMBER,
    SUBJECT_ID                    NUMBER,
    LAST_EXTRACT_RUN_ID           VARCHAR2(64),
    LAST_EXTRACT_RUN_TS           TIMESTAMP(6),
    CONSTRAINT FBX_QSTNR_QUESTION_PK PRIMARY KEY (QSTNR_PARTICIPANT_ID, QSTNR_QUESTION_ID)
);

CREATE INDEX FBX_QSTNR_QUESTION_N1 ON QSTNR_QUESTION_BC (QUESTIONNAIRE_ID);
CREATE INDEX FBX_QSTNR_QUESTION_N2 ON QSTNR_QUESTION_BC (SUBJECT_ID);
CREATE INDEX FBX_QSTNR_QUESTION_N3 ON QSTNR_QUESTION_BC (QSTNR_QUESTION_ID);
