
  CREATE TABLE "S_POS_CUSTOM_FLEX_BC"
   (	"JOB_ID" NUMBER NOT NULL ENABLE,
	"POS_DFF_ID" NUMBER,
	"STATE_POSITION_CODE" VARCHAR2(30),
	"DESC_STATE_POSITION_CODE" VARCHAR2(400),
	"POSITION_CATEGORY" VARCHAR2(100),
	"DESC_POSITION_CATEGORY" VARCHAR2(400),
	"WORK_SCHEDULE" VARCHAR2(100),
	"DESC_WORK_SCHEDULE" VARCHAR2(400),
	"PAYMENT_SCHEDULE" VARCHAR2(30),
	"DESC_PAYMENT_SCHEDULE" VARCHAR2(400),
	"STNTRT_CPTN_CT" VARCHAR2(30),
	"DESC_STNTRT_CPTN_CT" VARCHAR2(400),
	"SHORT_DESCRIPTION" VARCHAR2(400),
	"EFFECTIVE_START_RAW" VARCHAR2(50),
	"EFFECTIVE_START_TS" TIMESTAMP (6),
	"EFFECTIVE_END_RAW" VARCHAR2(50),
	"EFFECTIVE_END_TS" TIMESTAMP (6),
	"LAST_UPDATE_DATE_RAW" VARCHAR2(50),
	"LAST_UPDATE_DATE_TS" TIMESTAMP (6),
	"LAST_EXTRACT_RUN_ID" VARCHAR2(64),
	"LAST_EXTRACT_RUN_TS" TIMESTAMP (6)
   ) ;

  CREATE INDEX "S_POS_CUSTOM_FLEX_BC_N1" ON "S_POS_CUSTOM_FLEX_BC" ("JOB_ID", "POS_DFF_ID")
  ;
