CREATE TABLE S_QSTNR_RESPONSE_BC
(
    JOB_ID                  NUMBER          NOT NULL,
    QSTNR_RESPONSE_ID      NUMBER,
    QSTNR_PARTICIPANT_ID   NUMBER,
    RESPONSE_STATUS         VARCHAR2(10),
    ATTEMPT_NUM             NUMBER,
    SUBMITTED_DATE_RAW      VARCHAR2(50),
    SUBMITTED_DATE_TS       TIMESTAMP(6),
    QSTNR_QUESTION_ID      NUMBER,
    QSTN_RESPONSE_ID       NUMBER,
    ANSWER_CLOB             VARCHAR2(4000),
    ANSWER_ID               NUMBER,
    ANSWER_TYPE             VARCHAR2(30),
    SUBJECT_ID              NUMBER,
    LAST_UPDATE_DATE_RAW    VARCHAR2(50),
    LAST_UPDATE_DATE_TS     TIMESTAMP(6),
    LAST_EXTRACT_RUN_ID     VARCHAR2(64),
    LAST_EXTRACT_RUN_TS     TIMESTAMP(6)
);

CREATE INDEX S_QSTNR_RESPONSE_BC_N1 ON S_QSTNR_RESPONSE_BC (JOB_ID, QSTN_RESPONSE_ID);
CREATE INDEX S_QSTNR_RESPONSE_BC_N2 ON S_QSTNR_RESPONSE_BC (JOB_ID, QSTNR_PARTICIPANT_ID, QSTNR_QUESTION_ID);
