-- =============================================================================
-- HCM_ABSENCES_R
-- APEX REST Data Source sync table — module static ID: rest_sync_absences
-- Module code: HCM  |  Sync type: INCREMENTAL
-- APEX$ columns (APEX$RESOURCEKEY, APEX$SYNC_STEP_STATIC_ID,
--   APEX$ROW_SYNC_TIMESTAMP) are managed by APEX REST Data Sync
-- =============================================================================
CREATE TABLE HCM_ABSENCES_R (
    ABSENCECASEID                       NUMBER,
    ABSENCEENTRYBASICFLAG               VARCHAR2(5),
    ABSENCEPATTERNCD                    VARCHAR2(20),
    ABSENCESTATUSCD                     VARCHAR2(30),
    ABSENCETYPEID                       NUMBER,
    ABSENCETYPEREASONID                 NUMBER,
    AGREEMENTID                         NUMBER,
    APPROVALSTATUSCD                    VARCHAR2(30),
    AUTHSTATUSUPDATEDATE                DATE,
    BANDDTLID                           NUMBER,
    BLOCKEDLEAVECANDIDATE               VARCHAR2(30),
    CERTIFICATIONAUTHFLAG               VARCHAR2(5),
    CHILDEVENTTYPECD                    VARCHAR2(30),
    COMMENTS                            VARCHAR2(2000),
    CONDITIONSTARTDATE                  DATE,
    CONFIRMEDDATE                       DATE,
    CONSUMEDBYAGREEMENT                 VARCHAR2(30),
    CREATEDBY                           VARCHAR2(64),
    CREATIONDATE                        TIMESTAMP(6) WITH TIME ZONE,
    DISEASECODE                         VARCHAR2(250),
    DURATION                            NUMBER,
    EMPLOYEESHIFTFLAG                   VARCHAR2(5),
    ENDDATE                             DATE,
    ENDDATEDURATION                     NUMBER,
    ENDDATETIME                         TIMESTAMP(6) WITH TIME ZONE,
    ENDTIME                             VARCHAR2(30),
    ESTABLISHMENTDATE                   DATE,
    FREQUENCY                           VARCHAR2(30),
    INITIALREPORTBYID                   NUMBER,
    INITIALTIMELYNOTIFYFLAG             VARCHAR2(5),
    LASTUPDATEDATE                      TIMESTAMP(6) WITH TIME ZONE,
    LASTUPDATELOGIN                     VARCHAR2(32),
    LASTUPDATEDBY                       VARCHAR2(64),
    LATENOTIFYFLAG                      VARCHAR2(5),
    LEGALENTITYID                       NUMBER,
    LEGISLATIONCODE                     VARCHAR2(30),
    LEGISLATIVEDATAGROUPID              NUMBER,
    NOTIFICATIONDATE                    DATE,
    OBJECTVERSIONNUMBER                 NUMBER,
    OPENENDEDFLAG                       VARCHAR2(5),
    OVERRIDDEN                          VARCHAR2(10),
    PERSONABSENCEENTRYID                NUMBER,
    PERIODOFINCAPTOWORKFLAG             VARCHAR2(5),
    PERIODOFSERVICEID                   NUMBER,
    PERSONID                            NUMBER,
    PLANNEDENDDATE                      DATE,
    PROCESSINGSTATUS                    VARCHAR2(30),
    PROJECTID                           NUMBER,
    SINGLEDAYFLAG                       VARCHAR2(5),
    SOURCE                              VARCHAR2(10),
    SPLCONDITION                        VARCHAR2(1000),
    STARTDATE                           DATE,
    STARTDATEDURATION                   NUMBER,
    STARTDATETIME                       TIMESTAMP(6) WITH TIME ZONE,
    STARTTIME                           VARCHAR2(30),
    SUBMITTEDDATE                       DATE,
    TIMELINESSOVERRIDEDATE              DATE,
    UNITOFMEASURE                       VARCHAR2(30),
    USERMODE                            VARCHAR2(10),
    PERSONNUMBER                        VARCHAR2(32767),
    ABSENCETYPE                         VARCHAR2(32767),
    EMPLOYER                            VARCHAR2(32767),
    ABSENCEREASON                       VARCHAR2(32767),
    ABSENCEDISPSTATUS                   VARCHAR2(32767),
    ASSIGNMENTID                        NUMBER,
    DATASECURITYPERSONID                NUMBER,
    EFFECTIVEENDDATE                    DATE,
    EFFECTIVESTARTDATE                  DATE,
    AGREEMENTNAME                       VARCHAR2(32767),
    PAYMENTDETAIL                       VARCHAR2(32767),
    ASSIGNMENTNAME                      VARCHAR2(80),
    ASSIGNMENTNUMBER                    VARCHAR2(30),
    UNITOFMEASUREMEANING                VARCHAR2(80),
    FORMATTEDDURATION                   VARCHAR2(255),
    ABSENCEDISPSTATUSMEANING            VARCHAR2(255),
    ABSENCEUPDATABLEFLAG                VARCHAR2(5),
    APPROVALDATETIME                    TIMESTAMP(6) WITH TIME ZONE,
    ALLOWASSIGNMENTSELECTIONFLAG        VARCHAR2(5),
    ENDDATEDURATIONPREFERENCECODE       VARCHAR2(30),
    STARTDATEDURATIONPREFERENCECODE     VARCHAR2(30),
    STARTDATEDURATIONPREFERENCEMEANING  VARCHAR2(80),
    ENDDATEDURATIONPREFERENCEMEANING    VARCHAR2(80),
    IGNOREWARNINGFLAG                   VARCHAR2(5),
    CONSTRAINT HCM_ABSENCES_R_PK PRIMARY KEY (APEX$RESOURCEKEY)
);
