-- =============================================================================
-- RECEIVABLE_TRANSACTIONS_R
-- APEX REST Data Source sync table — module static ID: rest_sync_receivable_transactions
-- Module code: FIN  |  Sync type: INCREMENTAL
-- APEX$ columns (APEX$RESOURCEKEY, APEX$SYNC_STEP_STATIC_ID,
--   APEX$ROW_SYNC_TIMESTAMP) are managed by APEX REST Data Sync
-- =============================================================================
CREATE TABLE RECEIVABLE_TRANSACTIONS_R (
    CUSTOMERTRANSACTIONID                     NUMBER,
    DUEDATE                                   DATE,
    CONVERSIONDATE                            DATE,
    CONVERSIONRATE                            NUMBER,
    INVOICECURRENCYCODE                       VARCHAR2(15),
    SPECIALINSTRUCTIONS                       VARCHAR2(240),
    CROSSREFERENCE                            VARCHAR2(30),
    DOCUMENTNUMBER                            NUMBER,
    TRANSACTIONNUMBER                         VARCHAR2(20),
    TRANSACTIONDATE                           DATE,
    TRANSACTIONTYPE                           VARCHAR2(20),
    TRANSACTIONSOURCE                         VARCHAR2(50),
    BILLTOCUSTOMERNUMBER                      VARCHAR2(30),
    BILLTOSITE                                VARCHAR2(150),
    COMMENTS                                  VARCHAR2(1760),
    INTERNALNOTES                             VARCHAR2(240),
    PAYMENTTERMS                              VARCHAR2(15),
    LEGALENTITYIDENTIFIER                     VARCHAR2(30),
    CONVERSIONRATETYPE                        VARCHAR2(30),
    PURCHASEORDER                             VARCHAR2(50),
    PURCHASEORDERDATE                         DATE,
    PURCHASEORDERREVISION                     VARCHAR2(50),
    FIRSTPARTYREGISTRATIONNUMBER              VARCHAR2(30),
    THIRDPARTYREGISTRATIONNUMBER              VARCHAR2(50),
    INVOICINGRULE                             VARCHAR2(30),
    SHIPTOCUSTOMERNAME                        VARCHAR2(360),
    SHIPTOCUSTOMERNUMBER                      VARCHAR2(30),
    BILLINGDATE                               DATE,
    BILLTOPARTYID                             NUMBER,
    BUSINESSUNIT                              VARCHAR2(240),
    INVOICESTATUS                             VARCHAR2(32767),
    ACCOUNTINGDATE                            DATE,
    SHIPTOSITE                                VARCHAR2(30),
    PAYINGCUSTOMERNAME                        VARCHAR2(360),
    PAYINGCUSTOMERSITE                        VARCHAR2(150),
    BILLTOCUSTOMERNAME                        VARCHAR2(360),
    FREIGHTAMOUNT                             NUMBER,
    CARRIER                                   VARCHAR2(30),
    SHIPDATE                                  DATE,
    SHIPPINGREFERENCE                         VARCHAR2(50),
    BILLTOCONTACT                             VARCHAR2(360),
    SHIPTOCONTACT                             VARCHAR2(360),
    PRINTOPTION                               VARCHAR2(80),
    CREATEDBY                                 VARCHAR2(64),
    CREATIONDATE                              TIMESTAMP(6) WITH TIME ZONE,
    LASTUPDATEDBY                             VARCHAR2(64),
    LASTUPDATEDATE                            TIMESTAMP(6) WITH TIME ZONE,
    PAYINGCUSTOMERACCOUNT                     VARCHAR2(30),
    SOLDTOPARTYNUMBER                         VARCHAR2(30),
    REMITTOADDRESS                            VARCHAR2(960),
    DEFAULTTAXATIONCOUNTRY                    VARCHAR2(2),
    ENTEREDAMOUNT                             NUMBER,
    INVOICEBALANCEAMOUNT                      NUMBER,
    PREPAYMENT                                VARCHAR2(80),
    INTERCOMPANY                              VARCHAR2(80),
    DOCUMENTFISCALCLASSIFICATION              VARCHAR2(1996),
    BANKACCOUNTNUMBER                         VARCHAR2(100),
    CREDITCARDAUTHORIZATIONREQUESTIDENTIFIER  VARCHAR2(32767),
    CREDITCARDEXPIRATIONDATE                  VARCHAR2(32767),
    CREDITCARDISSUERCODE                      VARCHAR2(30),
    CREDITCARDTOKENNUMBER                     VARCHAR2(30),
    CREDITCARDVOICEAUTHORIZATIONCODE          VARCHAR2(100),
    CREDITCARDERRORCODE                       VARCHAR2(80),
    CREDITCARDERRORTEXT                       VARCHAR2(255),
    CARDHOLDERLASTNAME                        VARCHAR2(40),
    CARDHOLDERFIRSTNAME                       VARCHAR2(40),
    RECEIPTMETHOD                             VARCHAR2(30),
    SALESPERSONNUMBER                         VARCHAR2(255),
    STRUCTUREDPAYMENTREFERENCE                VARCHAR2(256),
    INVOICEPRINTED                            VARCHAR2(32767),
    LASTPRINTDATE                             DATE,
    ORIGINALPRINTDATE                         DATE,
    DELIVERYMETHOD                            VARCHAR2(32767),
    EMAIL                                     VARCHAR2(1000),
    ALLOWCOMPLETION                           VARCHAR2(1),
    CONTROLCOMPLETIONREASON                   VARCHAR2(32767),
    CONSTRAINT REST_RECEIVABLE_TRANSACTIONS_PK PRIMARY KEY (APEX$RESOURCEKEY)
);
