-- =============================================================================
-- GL JOURNAL BATCH  (GlJournalBatchExtractPVO)
-- Pipeline: L_GL_JOURNAL_BATCH_BC -> S_GL_JOURNAL_BATCH_BC -> GL_JOURNAL_BATCH_BC
-- PK: JOURNALBATCHJEBATCHID
-- =============================================================================

-- Landing Table (all VARCHAR2(4000))
CREATE TABLE L_GL_JOURNAL_BATCH_BC (
    JOURNALBATCHACCOUNTEDPERIODTYPE             VARCHAR2(4000),
    JOURNALBATCHACTUALFLAG                      VARCHAR2(4000),
    JOURNALBATCHAPPROVALSTATUSCODE              VARCHAR2(4000),
    JOURNALBATCHAPPROVEREMPLOYEEID              VARCHAR2(4000),
    JOURNALBATCHAVERAGEJOURNALFLAG              VARCHAR2(4000),
    JOURNALBATCHCHARTOFACCOUNTSID               VARCHAR2(4000),
    JOURNALBATCHCONTROLTOTAL                    VARCHAR2(4000),
    JOURNALBATCHCREATEDBY                       VARCHAR2(4000),
    JOURNALBATCHCREATIONDATE                    VARCHAR2(4000),
    JOURNALBATCHDATECREATED                     VARCHAR2(4000),
    JOURNALBATCHDEFAULTEFFECTIVEDATE            VARCHAR2(4000),
    JOURNALBATCHDEFAULTPERIODNAME               VARCHAR2(4000),
    JOURNALBATCHDESCRIPTION                     VARCHAR2(4000),
    JOURNALBATCHERRORMESSAGE                    VARCHAR2(4000),
    JOURNALBATCHFUNDSSTATUSCODE                 VARCHAR2(4000),
    JOURNALBATCHGROUPID                         VARCHAR2(4000),
    JOURNALBATCHJEBATCHID                       VARCHAR2(4000),
    JOURNALBATCHJESOURCE                        VARCHAR2(4000),
    JOURNALBATCHLASTUPDATEDATE                  VARCHAR2(4000),
    JOURNALBATCHLASTUPDATELOGIN                 VARCHAR2(4000),
    JOURNALBATCHLASTUPDATEDBY                   VARCHAR2(4000),
    JOURNALBATCHNAME                            VARCHAR2(4000),
    JOURNALBATCHOBJECTVERSIONNUMBER             VARCHAR2(4000),
    JOURNALBATCHPARENTJEBATCHID                 VARCHAR2(4000),
    JOURNALBATCHPERIODSETNAME                   VARCHAR2(4000),
    JOURNALBATCHPOSTEDDATE                      VARCHAR2(4000),
    JOURNALBATCHPOSTINGRUNID                    VARCHAR2(4000),
    JOURNALBATCHREQUESTID                       VARCHAR2(4000),
    JOURNALBATCHRUNNINGTOTALACCOUNTEDCR         VARCHAR2(4000),
    JOURNALBATCHRUNNINGTOTALACCOUNTEDDR         VARCHAR2(4000),
    JOURNALBATCHRUNNINGTOTALCR                  VARCHAR2(4000),
    JOURNALBATCHRUNNINGTOTALDR                  VARCHAR2(4000),
    JOURNALBATCHSTATUS                          VARCHAR2(4000)
);

-- =============================================================================
-- Staging Table
-- =============================================================================
CREATE TABLE S_GL_JOURNAL_BATCH_BC (
    JOB_ID                                      NUMBER NOT NULL,
    JOURNALBATCHJEBATCHID                       NUMBER,
    JOURNALBATCHACCOUNTEDPERIODTYPE             VARCHAR2(80),
    JOURNALBATCHACTUALFLAG                      VARCHAR2(1),
    JOURNALBATCHAPPROVALSTATUSCODE              VARCHAR2(80),
    JOURNALBATCHAPPROVEREMPLOYEEID              NUMBER,
    JOURNALBATCHAVERAGEJOURNALFLAG              VARCHAR2(1),
    JOURNALBATCHCHARTOFACCOUNTSID               NUMBER,
    JOURNALBATCHCREATIONDATE_RAW                VARCHAR2(50),
    JOURNALBATCHCREATIONDATE_TS                 TIMESTAMP(6),
    JOURNALBATCHDATECREATED_RAW                 VARCHAR2(50),
    JOURNALBATCHDATECREATED_TS                  TIMESTAMP(6),
    JOURNALBATCHDEFAULTEFFECTIVEDATE_RAW        VARCHAR2(50),
    JOURNALBATCHDEFAULTEFFECTIVEDATE_TS         TIMESTAMP(6),
    JOURNALBATCHDEFAULTPERIODNAME               VARCHAR2(400),
    JOURNALBATCHDESCRIPTION                     VARCHAR2(400),
    JOURNALBATCHFUNDSSTATUSCODE                 VARCHAR2(80),
    JOURNALBATCHGROUPID                         NUMBER,
    JOURNALBATCHLASTUPDATEDATE_RAW              VARCHAR2(50),
    JOURNALBATCHLASTUPDATEDATE_TS               TIMESTAMP(6),
    JOURNALBATCHLASTUPDATELOGIN_RAW             VARCHAR2(50),
    JOURNALBATCHLASTUPDATELOGIN_TS              TIMESTAMP(6),
    JOURNALBATCHLASTUPDATEDBY_RAW               VARCHAR2(50),
    JOURNALBATCHLASTUPDATEDBY_TS                TIMESTAMP(6),
    JOURNALBATCHNAME                            VARCHAR2(400),
    JOURNALBATCHOBJECTVERSIONNUMBER             VARCHAR2(80),
    JOURNALBATCHPARENTJEBATCHID                 NUMBER,
    JOURNALBATCHPERIODSETNAME                   VARCHAR2(400),
    JOURNALBATCHPOSTEDDATE_RAW                  VARCHAR2(50),
    JOURNALBATCHPOSTEDDATE_TS                   TIMESTAMP(6),
    JOURNALBATCHPOSTINGRUNID                    NUMBER,
    JOURNALBATCHREQUESTID                       NUMBER,
    JOURNALBATCHSTATUS                          VARCHAR2(80),
    LAST_EXTRACT_RUN_ID                         VARCHAR2(64),
    LAST_EXTRACT_RUN_TS                         TIMESTAMP(6)
);

CREATE INDEX S_GL_JOURNAL_BATCH_BC_N1 ON S_GL_JOURNAL_BATCH_BC (JOB_ID, JOURNALBATCHJEBATCHID);

-- =============================================================================
-- Final Table
-- =============================================================================
CREATE TABLE GL_JOURNAL_BATCH_BC (
    JOURNALBATCHJEBATCHID                       NUMBER,
    JOURNALBATCHACCOUNTEDPERIODTYPE             VARCHAR2(80),
    JOURNALBATCHACTUALFLAG                      VARCHAR2(1),
    JOURNALBATCHAPPROVALSTATUSCODE              VARCHAR2(80),
    JOURNALBATCHAPPROVEREMPLOYEEID              NUMBER,
    JOURNALBATCHAVERAGEJOURNALFLAG              VARCHAR2(1),
    JOURNALBATCHCHARTOFACCOUNTSID               NUMBER,
    JOURNALBATCHCREATIONDATE_TS                 TIMESTAMP(6),
    JOURNALBATCHDATECREATED_TS                  TIMESTAMP(6),
    JOURNALBATCHDEFAULTEFFECTIVEDATE_TS         TIMESTAMP(6),
    JOURNALBATCHDEFAULTPERIODNAME               VARCHAR2(400),
    JOURNALBATCHDESCRIPTION                     VARCHAR2(400),
    JOURNALBATCHFUNDSSTATUSCODE                 VARCHAR2(80),
    JOURNALBATCHGROUPID                         NUMBER,
    JOURNALBATCHLASTUPDATEDATE_TS               TIMESTAMP(6),
    JOURNALBATCHLASTUPDATELOGIN_TS              TIMESTAMP(6),
    JOURNALBATCHLASTUPDATEDBY_TS                TIMESTAMP(6),
    JOURNALBATCHNAME                            VARCHAR2(400),
    JOURNALBATCHOBJECTVERSIONNUMBER             VARCHAR2(80),
    JOURNALBATCHPARENTJEBATCHID                 NUMBER,
    JOURNALBATCHPERIODSETNAME                   VARCHAR2(400),
    JOURNALBATCHPOSTEDDATE_TS                   TIMESTAMP(6),
    JOURNALBATCHPOSTINGRUNID                    NUMBER,
    JOURNALBATCHREQUESTID                       NUMBER,
    JOURNALBATCHSTATUS                          VARCHAR2(80),
    LAST_EXTRACT_RUN_ID                         VARCHAR2(64),
    LAST_EXTRACT_RUN_TS                         TIMESTAMP(6),
    CONSTRAINT FBX_GL_JOURNAL_BATCH_PK PRIMARY KEY (JOURNALBATCHJEBATCHID)
);

CREATE INDEX GL_JOURNAL_BATCH_BC_N1 ON GL_JOURNAL_BATCH_BC (JOURNALBATCHSTATUS, JOURNALBATCHPOSTEDDATE_TS);
