-- =============================================================================
-- LANDING TABLE: L_AP_INVOICE_HDR_BC
-- =============================================================================
-- COPY_DATA loads the raw CSV into this table.
-- The load procedure then cherry-picks columns into stg_fbx_ap_invoice_hdr.
--
-- SETUP (two steps):
--   1. Create the external table (defines the CSV structure)
--   2. Create the landing table as a copy of the external table structure
--
-- IF BICC SCHEMA CHANGES:
--   DROP TABLE L_AP_INVOICE_HDR_BC;
--   DROP TABLE EXT_AP_INVOICE_HDR_BC;
--   Re-run Step 1 with updated column_list, then re-run Step 2.
-- =============================================================================


-- Step 1: Create external table (one-time, defines CSV structure)
-- This is the source of truth for column names and order.
-- UPDATE the file_uri_list to point at an existing extracted CSV before running.
BEGIN
  DBMS_CLOUD.CREATE_EXTERNAL_TABLE(
    table_name      => 'EXT_AP_INVOICE_HDR_BC',
    credential_name => '<OCI_CREDENTIAL_NAME>',
    file_uri_list   => 'https://objectstorage.us-ashburn-1.oraclecloud.com/n/<OCI_NAMESPACE>/b/<OCI_BUCKET_NAME>/o/ap_invoice_hdr_unzipped.csv',
    format          => json_object(
                         'type' value 'csv',
                         'skipheaders' value '1'
                       ),
    column_list     => 'ATTACHMENTFLAG VARCHAR2(4000),DISTRIBUTIONSETORGID VARCHAR2(4000),DOCSEQCATDESCRIPTION VARCHAR2(4000),DOCSEQCATNAME VARCHAR2(4000),DOCSEQUENCENAME VARCHAR2(4000),FIRSTPARTYTAXREGISTRATIONLASTUPDATEDATE VARCHAR2(4000),FIRSTPARTYTAXREGISTRATIONREGISTRATIONNUMBER VARCHAR2(4000),INVDISTCOUNT VARCHAR2(4000),INVDISTDRAFTCOUNT VARCHAR2(4000),INVDISTPOSTEDCOUNT VARCHAR2(4000),INVDISTSELECTCOUNT VARCHAR2(4000),INVHDRCRINVINVOICENUM VARCHAR2(4000),INVHDRTAXRELINVINVOICENUM VARCHAR2(4000),INVPREPAYHISTORYCOUNT VARCHAR2(4000),INVSELFASSESTAXDISTCOUNT VARCHAR2(4000),INVSELFASSESTAXDISTPOSTEDCOUNT VARCHAR2(4000),INVSELFASSESTAXDISTSELECTCOUNT VARCHAR2(4000),INVOICEBATCHBATCHID VARCHAR2(4000),INVOICEBATCHBATCHNAME VARCHAR2(4000),INVOICECONVERSIONTYPEUSERCONVERSIONTYPE VARCHAR2(4000),INVOICEHDRACCOUNTINGSTATUSCODE VARCHAR2(4000),INVOICEHDRTRANSACTIONDEADLINE VARCHAR2(4000),INVOICEHDRVALIDATIONSTATUSCODE VARCHAR2(4000),INVOICEHEADERAMOUNTAPPLICABLETODISCOUNT VARCHAR2(4000),INVOICEHEADERAMOUNTPAID VARCHAR2(4000),INVOICEHEADERAPPROVALDESCRIPTION VARCHAR2(4000),INVOICEHEADERAPPROVALITERATION VARCHAR2(4000),INVOICEHEADERAPPROVALSTATUS VARCHAR2(4000),INVOICEHEADERBASEAMOUNT VARCHAR2(4000),INVOICEHEADERBUDGETDATE VARCHAR2(4000),INVOICEHEADERCANCELLEDAMOUNT VARCHAR2(4000),INVOICEHEADERCANCELLEDBY VARCHAR2(4000),INVOICEHEADERCANCELLEDDATE VARCHAR2(4000),INVOICEHEADERCONTROLAMOUNT VARCHAR2(4000),INVOICEHEADERCORRECTIONPERIOD VARCHAR2(4000),INVOICEHEADERCORRECTIONYEAR VARCHAR2(4000),INVOICEHEADERCREATEDBY VARCHAR2(4000),INVOICEHEADERCREATIONDATE VARCHAR2(4000),INVOICEHEADERDESCRIPTION VARCHAR2(4000),INVOICEHEADERDISCOUNTAMOUNTTAKEN VARCHAR2(4000),INVOICEHEADERDOCCATEGORYCODE VARCHAR2(4000),INVOICEHEADERDOCSEQUENCEVALUE VARCHAR2(4000),INVOICEHEADEREARLIESTSETTLEMENTDATE VARCHAR2(4000),INVOICEHEADEREXCHANGEDATE VARCHAR2(4000),INVOICEHEADEREXCHANGERATE VARCHAR2(4000),INVOICEHEADEREXCLUDEFREIGHTFROMDISCOUNT VARCHAR2(4000),INVOICEHEADEREXCLUSIVEPAYMENTFLAG VARCHAR2(4000),INVOICEHEADERFREIGHTAMOUNT VARCHAR2(4000),INVOICEHEADERFUNDSSTATUS VARCHAR2(4000),INVOICEHEADERGLDATE VARCHAR2(4000),INVOICEHEADERGOODSRECEIVEDDATE VARCHAR2(4000),INVOICEHEADERIMPORTDOCUMENTDATE VARCHAR2(4000),INVOICEHEADERINTERCOMPANYFLAG VARCHAR2(4000),INVOICEHEADERINVOICEAMOUNT VARCHAR2(4000),INVOICEHEADERINVOICECURRENCYCODE VARCHAR2(4000),INVOICEHEADERINVOICEDATE VARCHAR2(4000),INVOICEHEADERINVOICENUM VARCHAR2(4000),INVOICEHEADERINVOICERECEIVEDDATE VARCHAR2(4000),INVOICEHEADERINVOICETYPELOOKUPCODE VARCHAR2(4000),INVOICEHEADERLASTUPDATEDATE VARCHAR2(4000),INVOICEHEADERLASTUPDATEDBY VARCHAR2(4000),INVOICEHEADERNETOFRETAINAGEFLAG VARCHAR2(4000),INVOICEHEADERPAYGROUPLOOKUPCODE VARCHAR2(4000),INVOICEHEADERPAYMENTAMOUNTTOTAL VARCHAR2(4000),INVOICEHEADERPAYMENTCROSSRATE VARCHAR2(4000),INVOICEHEADERPAYMENTCROSSRATEDATE VARCHAR2(4000),INVOICEHEADERPAYMENTCROSSRATETYPE VARCHAR2(4000),INVOICEHEADERPAYMENTCURRENCYCODE VARCHAR2(4000),INVOICEHEADERPAYMENTREASONCOMMENTS VARCHAR2(4000),INVOICEHEADERPAYMENTSTATUSFLAG VARCHAR2(4000),INVOICEHEADERPORTOFENTRYCODE VARCHAR2(4000),INVOICEHEADERPOSTINGSTATUS VARCHAR2(4000),INVOICEHEADERRELEASEAMOUNTNETOFTAX VARCHAR2(4000),INVOICEHEADERROUTINGATTRIBUTE1 VARCHAR2(4000),INVOICEHEADERROUTINGATTRIBUTE2 VARCHAR2(4000),INVOICEHEADERROUTINGATTRIBUTE3 VARCHAR2(4000),INVOICEHEADERROUTINGATTRIBUTE4 VARCHAR2(4000),INVOICEHEADERROUTINGSTATUSLOOKUPCODE VARCHAR2(4000),INVOICEHEADERSELFASSESSEDTAXAMOUNT VARCHAR2(4000),INVOICEHEADERSETTLEMENTPRIORITY VARCHAR2(4000),INVOICEHEADERSUPPLIERTAXEXCHANGERATE VARCHAR2(4000),INVOICEHEADERSUPPLIERTAXINVOICEDATE VARCHAR2(4000),INVOICEHEADERSUPPLIERTAXINVOICENUMBER VARCHAR2(4000),INVOICEHEADERTAXINVOICEINTERNALSEQ VARCHAR2(4000),INVOICEHEADERTAXINVOICERECORDINGDATE VARCHAR2(4000),INVOICEHEADERTAXATIONCOUNTRY VARCHAR2(4000),INVOICEHEADERTERMSDATE VARCHAR2(4000),INVOICEHEADERTOTALTAXAMOUNT VARCHAR2(4000),INVOICEHEADERUNIQUEREMITTANCEIDENTIFIER VARCHAR2(4000),INVOICEHEADERVOUCHERNUM VARCHAR2(4000),INVOICEHEADERWFAPPROVALSTATUS VARCHAR2(4000),INVOICEID VARCHAR2(4000),PARTYLASTUPDATEDATE VARCHAR2(4000),PARTYPARTYNAME VARCHAR2(4000),PARTYSITELASTUPDATEDATE VARCHAR2(4000),PARTYSITEPARTYSITENAME VARCHAR2(4000),PERSONCANCELLEDBYDISPLAYNAME VARCHAR2(4000),PERSONCREATEDBYDISPLAYNAME VARCHAR2(4000),PERSONCREATEDBYEFFECTIVESTARTDATE VARCHAR2(4000),PERSONNAMEDISPLAYNAME VARCHAR2(4000),PERSONNAMEEFFECTIVESTARTDATE VARCHAR2(4000),PERSONUPDATEDBYDISPLAYNAME VARCHAR2(4000),PERSONUPDATEDBYEFFECTIVESTARTDATE VARCHAR2(4000),PURCHASEORDERCLOSEDDATE VARCHAR2(4000),PURCHASEORDERSEGMENT1 VARCHAR2(4000),THIRDPARTYTAXREGISTRATIONLASTUPDATEDATE1 VARCHAR2(4000),THIRDPARTYTAXREGISTRATIONREGISTRATIONNUMBER1 VARCHAR2(4000)'
  );
END;
/

-- Step 2: Create landing table from external table structure (empty copy)
CREATE TABLE L_AP_INVOICE_HDR_BC AS
SELECT * FROM EXT_AP_INVOICE_HDR_BC WHERE 1=0;
