-- =============================================================================
-- LANDING TABLE: L_AP_DISBURSEMENT_BC
-- =============================================================================
-- Source: FscmTopModelAM.FinExtractAM.ApBiccExtractAM.DisbursementHeaderExtractPVO
-- Underlying table: AP_CHECKS_ALL
-- One row per physical payment (check or EFT disbursement).
-- COPY_DATA loads the raw CSV into this table.
-- The load procedure then cherry-picks columns into S_AP_DISBURSEMENT_BC.
--
-- SETUP (three steps):
--   0. Extract CSV from the BICC ZIP (pkg_bicc_common.extract_and_stage_csv)
--   1. Create the external table (defines the CSV structure)
--   2. Create the landing table as a copy of the external table structure
--
-- IF BICC SCHEMA CHANGES:
--   DROP TABLE L_AP_DISBURSEMENT_BC;
--   DROP TABLE EXT_AP_DISBURSEMENT_BC;
--   Re-run Step 1 with updated column_list, then re-run Step 2.
-- =============================================================================


-- Step 0: Extract CSV from ZIP and upload to Object Storage
BEGIN
  pkg_bicc_common.extract_and_stage_csv(
      p_file_name    => 'file_fscmtopmodelam_finextractam_apbiccextractam_disbursementheaderextractpvo-batch325884033-20260414_221525.zip',
      p_staging_name => 'staging/ap_disbursement_current.csv'
  );
END;
/


-- Step 1: Create external table (one-time, defines CSV structure)
-- 101 columns, alphabetical order per BICC convention.
BEGIN
  DBMS_CLOUD.CREATE_EXTERNAL_TABLE(
    table_name      => 'EXT_AP_DISBURSEMENT_BC',
    credential_name => '<OCI_CREDENTIAL_NAME>',
    file_uri_list   => 'https://objectstorage.us-ashburn-1.oraclecloud.com/n/<OCI_NAMESPACE>/b/<OCI_BUCKET_NAME>/o/staging/ap_disbursement_current.csv',
    format          => json_object(
                         'type' value 'csv',
                         'skipheaders' value '1'
                       ),
    column_list     => 'APCHECKSALLACTUALVALUEDATE VARCHAR2(4000),APCHECKSALLADDRESSLINE1 VARCHAR2(4000),APCHECKSALLADDRESSLINE2 VARCHAR2(4000),APCHECKSALLADDRESSLINE3 VARCHAR2(4000),APCHECKSALLADDRESSLINE4 VARCHAR2(4000),APCHECKSALLADDRESSSTYLE VARCHAR2(4000),APCHECKSALLAMOUNT VARCHAR2(4000),APCHECKSALLANTICIPATEDVALUEDATE VARCHAR2(4000),APCHECKSALLBANKACCOUNTNAME VARCHAR2(4000),APCHECKSALLBANKACCOUNTNUM VARCHAR2(4000),APCHECKSALLBANKACCOUNTTYPE VARCHAR2(4000),APCHECKSALLBANKCHARGEBEARER VARCHAR2(4000),APCHECKSALLBANKNUM VARCHAR2(4000),APCHECKSALLBASEAMOUNT VARCHAR2(4000),APCHECKSALLCEBANKACCTUSEID VARCHAR2(4000),APCHECKSALLCHECKDATE VARCHAR2(4000),APCHECKSALLCHECKFORMATID VARCHAR2(4000),APCHECKSALLCHECKID VARCHAR2(4000),APCHECKSALLCHECKNUMBER VARCHAR2(4000),APCHECKSALLCHECKSTOCKID VARCHAR2(4000),APCHECKSALLCHECKVOUCHERNUM VARCHAR2(4000),APCHECKSALLCHECKRUNID VARCHAR2(4000),APCHECKSALLCHECKRUNNAME VARCHAR2(4000),APCHECKSALLCITY VARCHAR2(4000),APCHECKSALLCLEAREDAMOUNT VARCHAR2(4000),APCHECKSALLCLEAREDBASEAMOUNT VARCHAR2(4000),APCHECKSALLCLEAREDCHARGESAMOUNT VARCHAR2(4000),APCHECKSALLCLEAREDCHARGESBASEAMOUNT VARCHAR2(4000),APCHECKSALLCLEAREDDATE VARCHAR2(4000),APCHECKSALLCLEAREDERRORAMOUNT VARCHAR2(4000),APCHECKSALLCLEAREDERRORBASEAMOUNT VARCHAR2(4000),APCHECKSALLCLEAREDEXCHANGEDATE VARCHAR2(4000),APCHECKSALLCLEAREDEXCHANGERATE VARCHAR2(4000),APCHECKSALLCLEAREDEXCHANGERATETYPE VARCHAR2(4000),APCHECKSALLCOMPLETEDPMTSGROUPID VARCHAR2(4000),APCHECKSALLCOUNTRY VARCHAR2(4000),APCHECKSALLCOUNTY VARCHAR2(4000),APCHECKSALLCREATEDBY VARCHAR2(4000),APCHECKSALLCREATIONDATE VARCHAR2(4000),APCHECKSALLCURRENCYCODE VARCHAR2(4000),APCHECKSALLDESCRIPTION VARCHAR2(4000),APCHECKSALLDOCCATEGORYCODE VARCHAR2(4000),APCHECKSALLDOCSEQUENCEID VARCHAR2(4000),APCHECKSALLDOCSEQUENCEVALUE VARCHAR2(4000),APCHECKSALLEMPLOYEEADDRESSCODE VARCHAR2(4000),APCHECKSALLEXCHANGEDATE VARCHAR2(4000),APCHECKSALLEXCHANGERATE VARCHAR2(4000),APCHECKSALLEXCHANGERATETYPE VARCHAR2(4000),APCHECKSALLEXTERNALBANKACCOUNTID VARCHAR2(4000),APCHECKSALLFUTUREPAYDUEDATE VARCHAR2(4000),APCHECKSALLIBANNUMBER VARCHAR2(4000),APCHECKSALLLASTUPDATEDATE VARCHAR2(4000),APCHECKSALLLASTUPDATELOGIN VARCHAR2(4000),APCHECKSALLLASTUPDATEDBY VARCHAR2(4000),APCHECKSALLLEGALENTITYID VARCHAR2(4000),APCHECKSALLLOGICALGROUPREFERENCE VARCHAR2(4000),APCHECKSALLMATURITYEXCHANGEDATE VARCHAR2(4000),APCHECKSALLMATURITYEXCHANGERATE VARCHAR2(4000),APCHECKSALLMATURITYEXCHANGERATETYPE VARCHAR2(4000),APCHECKSALLOBJECTVERSIONNUMBER VARCHAR2(4000),APCHECKSALLORGID VARCHAR2(4000),APCHECKSALLPARTYID VARCHAR2(4000),APCHECKSALLPARTYSITEID VARCHAR2(4000),APCHECKSALLPAYMENTDOCUMENTID VARCHAR2(4000),APCHECKSALLPAYMENTID VARCHAR2(4000),APCHECKSALLPAYMENTINSTRUCTIONID VARCHAR2(4000),APCHECKSALLPAYMENTMETHODCODE VARCHAR2(4000),APCHECKSALLPAYMENTMETHODLOOKUPCODE VARCHAR2(4000),APCHECKSALLPAYMENTPROFILEID VARCHAR2(4000),APCHECKSALLPAYMENTTYPEFLAG VARCHAR2(4000),APCHECKSALLPOSITIVEPAYSTATUSCODE VARCHAR2(4000),APCHECKSALLPROVINCE VARCHAR2(4000),APCHECKSALLRECONFLAG VARCHAR2(4000),APCHECKSALLRECONCILIATIONBATCHID VARCHAR2(4000),APCHECKSALLRELATIONSHIPID VARCHAR2(4000),APCHECKSALLRELEASEDBY VARCHAR2(4000),APCHECKSALLRELEASEDDATE VARCHAR2(4000),APCHECKSALLREMITTOADDRESSID VARCHAR2(4000),APCHECKSALLREMITTOADDRESSNAME VARCHAR2(4000),APCHECKSALLREMITTOSUPPLIERID VARCHAR2(4000),APCHECKSALLREMITTOSUPPLIERNAME VARCHAR2(4000),APCHECKSALLREQUESTID VARCHAR2(4000),APCHECKSALLSETTLEMENTPRIORITY VARCHAR2(4000),APCHECKSALLSTAMPDUTYAMT VARCHAR2(4000),APCHECKSALLSTAMPDUTYBASEAMT VARCHAR2(4000),APCHECKSALLSTATE VARCHAR2(4000),APCHECKSALLSTATUSLOOKUPCODE VARCHAR2(4000),APCHECKSALLSTOPPEDBY VARCHAR2(4000),APCHECKSALLSTOPPEDDATE VARCHAR2(4000),APCHECKSALLTRANSFERPRIORITY VARCHAR2(4000),APCHECKSALLTREASURYPAYDATE VARCHAR2(4000),APCHECKSALLTREASURYPAYNUMBER VARCHAR2(4000),APCHECKSALLUSSGLTRANSACTIONCODE VARCHAR2(4000),APCHECKSALLUSSGLTRXCODECONTEXT VARCHAR2(4000),APCHECKSALLVENDORID VARCHAR2(4000),APCHECKSALLVENDORNAME VARCHAR2(4000),APCHECKSALLVENDORSITECODE VARCHAR2(4000),APCHECKSALLVENDORSITEID VARCHAR2(4000),APCHECKSALLVOIDDATE VARCHAR2(4000),APCHECKSALLXCURRRATETYPE VARCHAR2(4000),APCHECKSALLZIP VARCHAR2(4000)'
  );
END;
/

-- Step 2: Create landing table from the external table structure
CREATE TABLE L_AP_DISBURSEMENT_BC AS SELECT * FROM EXT_AP_DISBURSEMENT_BC WHERE 1=0;
