-- =============================================================================
-- LANDING TABLE: L_GL_CODE_COMB_BC
-- =============================================================================
-- Source: FscmTopModelAM.FinExtractAM.GlBiccExtractAM.CodeCombinationExtractPVO
-- COPY_DATA loads the raw CSV into this table.
-- The load procedure then cherry-picks columns into stg_fbx_gl_code_comb.
--
-- SETUP (three steps):
--   0. Extract CSV from the BICC ZIP (pkg_bicc_common.extract_and_stage_csv)
--   1. Create the external table (defines the CSV structure)
--   2. Create the landing table as a copy of the external table structure
--
-- IF BICC SCHEMA CHANGES:
--   DROP TABLE L_GL_CODE_COMB_BC;
--   DROP TABLE EXT_GL_CODE_COMB_BC;
--   Re-run Step 1 with updated column_list, then re-run Step 2.
-- =============================================================================


-- Step 0: Extract CSV from ZIP and upload to Object Storage
-- Replace the file name below with the actual BICC ZIP from your extract.
BEGIN
  pkg_bicc_common.extract_and_stage_csv(
      p_file_name    => 'file_fscmtopmodelam_finextractam_glbiccextractam_codecombinationextractpvo-batch1008232491-20260309_183828.zip',
      p_staging_name => 'staging/gl_code_comb_current.csv'
  );
END;
/


-- Step 1: Create external table (one-time, defines CSV structure)
-- Column order is alphabetical (standard BICC Fusion extract).
BEGIN
  DBMS_CLOUD.CREATE_EXTERNAL_TABLE(
    table_name      => 'EXT_GL_CODE_COMB_BC',
    credential_name => '<OCI_CREDENTIAL_NAME>',
    file_uri_list   => 'https://objectstorage.us-ashburn-1.oraclecloud.com/n/<OCI_NAMESPACE>/b/<OCI_BUCKET_NAME>/o/staging/gl_code_comb_current.csv',
    format          => json_object(
                         'type' value 'csv',
                         'skipheaders' value '1'
                       ),
    column_list     => 'CODECOMBINATIONACCOUNTTYPE VARCHAR2(4000),CODECOMBINATIONALTERNATECODECOMBINATIONID VARCHAR2(4000),CODECOMBINATIONCHARTOFACCOUNTSID VARCHAR2(4000),CODECOMBINATIONCODECOMBINATIONID VARCHAR2(4000),CODECOMBINATIONCREATEDBY VARCHAR2(4000),CODECOMBINATIONCREATIONDATE VARCHAR2(4000),CODECOMBINATIONDETAILBUDGETINGALLOWEDFLAG VARCHAR2(4000),CODECOMBINATIONDETAILPOSTINGALLOWEDFLAG VARCHAR2(4000),CODECOMBINATIONENABLEDFLAG VARCHAR2(4000),CODECOMBINATIONENDDATEACTIVE VARCHAR2(4000),CODECOMBINATIONFINANCIALCATEGORY VARCHAR2(4000),CODECOMBINATIONJGZZRECONFLAG VARCHAR2(4000),CODECOMBINATIONLASTUPDATEDATE VARCHAR2(4000),CODECOMBINATIONLASTUPDATELOGIN VARCHAR2(4000),CODECOMBINATIONLASTUPDATEDBY VARCHAR2(4000),CODECOMBINATIONOBJECTVERSIONNUMBER VARCHAR2(4000),CODECOMBINATIONPRESERVEFLAG VARCHAR2(4000),CODECOMBINATIONSEGMENT1 VARCHAR2(4000),CODECOMBINATIONSEGMENT10 VARCHAR2(4000),CODECOMBINATIONSEGMENT11 VARCHAR2(4000),CODECOMBINATIONSEGMENT12 VARCHAR2(4000),CODECOMBINATIONSEGMENT13 VARCHAR2(4000),CODECOMBINATIONSEGMENT14 VARCHAR2(4000),CODECOMBINATIONSEGMENT15 VARCHAR2(4000),CODECOMBINATIONSEGMENT16 VARCHAR2(4000),CODECOMBINATIONSEGMENT17 VARCHAR2(4000),CODECOMBINATIONSEGMENT18 VARCHAR2(4000),CODECOMBINATIONSEGMENT19 VARCHAR2(4000),CODECOMBINATIONSEGMENT2 VARCHAR2(4000),CODECOMBINATIONSEGMENT20 VARCHAR2(4000),CODECOMBINATIONSEGMENT21 VARCHAR2(4000),CODECOMBINATIONSEGMENT22 VARCHAR2(4000),CODECOMBINATIONSEGMENT23 VARCHAR2(4000),CODECOMBINATIONSEGMENT24 VARCHAR2(4000),CODECOMBINATIONSEGMENT25 VARCHAR2(4000),CODECOMBINATIONSEGMENT26 VARCHAR2(4000),CODECOMBINATIONSEGMENT27 VARCHAR2(4000),CODECOMBINATIONSEGMENT28 VARCHAR2(4000),CODECOMBINATIONSEGMENT29 VARCHAR2(4000),CODECOMBINATIONSEGMENT3 VARCHAR2(4000),CODECOMBINATIONSEGMENT30 VARCHAR2(4000),CODECOMBINATIONSEGMENT4 VARCHAR2(4000),CODECOMBINATIONSEGMENT5 VARCHAR2(4000),CODECOMBINATIONSEGMENT6 VARCHAR2(4000),CODECOMBINATIONSEGMENT7 VARCHAR2(4000),CODECOMBINATIONSEGMENT8 VARCHAR2(4000),CODECOMBINATIONSEGMENT9 VARCHAR2(4000),CODECOMBINATIONSTARTDATEACTIVE VARCHAR2(4000),CODECOMBINATIONSUMMARYFLAG VARCHAR2(4000)'
  );
END;
/

-- Step 2: Create landing table from the external table structure
CREATE TABLE L_GL_CODE_COMB_BC AS SELECT * FROM EXT_GL_CODE_COMB_BC WHERE 1=0;
