
  CREATE TABLE "S_PO_HDR_BC" 
   (	"JOB_ID" NUMBER NOT NULL ENABLE, 
	"POHEADERID" NUMBER, 
	"PO_NUMBER" VARCHAR2(30), 
	"REVISIONNUM" NUMBER, 
	"PO_TYPE" VARCHAR2(30), 
	"DOCUMENTSTATUS" VARCHAR2(60), 
	"APPROVEDFLAG" VARCHAR2(1), 
	"PRCBUID" NUMBER, 
	"VENDORID" NUMBER, 
	"VENDORSITEID" NUMBER, 
	"VENDOR_ORDER_NUM" VARCHAR2(240), 
	"CURRENCYCODE" VARCHAR2(15), 
	"AMOUNTLIMIT" NUMBER, 
	"AMOUNTRELEASED" NUMBER, 
	"BLANKETTOTALAMOUNT" NUMBER, 
	"STARTDATE_RAW" VARCHAR2(50), 
	"CREATIONDATE_RAW" VARCHAR2(50), 
	"LASTUPDATEDATE_RAW" VARCHAR2(50), 
	"CLOSEDDATE_RAW" VARCHAR2(50), 
	"STARTDATE_TS" TIMESTAMP (6), 
	"CREATIONDATE_TS" TIMESTAMP (6), 
	"LASTUPDATEDATE_TS" TIMESTAMP (6), 
	"CLOSEDDATE_TS" TIMESTAMP (6), 
	"LASTUPDATEDBY" VARCHAR2(255), 
	"OBJECTVERSIONNUMBER" NUMBER, 
	"LAST_EXTRACT_RUN_ID" VARCHAR2(64), 
	"LAST_EXTRACT_RUN_TS" TIMESTAMP (6)
   ) ;

  CREATE INDEX "S_PO_HDR_BC_N1" ON "S_PO_HDR_BC" ("JOB_ID", "POHEADERID") 
  ;

  CREATE INDEX "S_PO_HDR_BC_N2" ON "S_PO_HDR_BC" ("JOB_ID", "PO_NUMBER") 
  ;